### ISSUE TITLE
中奖检查时增加回复信息读取

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#102]
### 描述

目前中奖信息只获取@和私信，希望能再加个回复信息的读取，和私信一样能设置页数。通常小号是没有人回复的，偶尔个别开奖是通过直接评论区回复开奖的。如果影响账号风控或者安全就这功能就当我没说。

**Comment by ypw96** [comment]
另外在读取@信息的时候，能否根据未读@数量，拼接推送消息时只推送最新的未读@信息，推送全部太多了觉得

**Comment by jzcangshu** [comment]
> 另外在读取@信息的时候，能否根据未读@数量，拼接推送消息时只推送最新的未读@信息，推送全部太多了觉得
已实现 但是可能跟我之前写的issues一样 有重复推送已读无效的问题
