### ISSUE TITLE
部署在https://replit.com/languages/nodejs上？

### ISSUE THREAD

**Issue by 8yn** [shanmiteko/LotteryAutoScript#106]
### 描述

https://replit.com/languages/nodejs

**Comment by shanmiteko** [comment]
Import from GitHub不就行了，改一下那两个配置文件名

**Comment by oyua** [comment]
然后就不知道怎么做了

**Comment by shanmiteko** [comment]
跟本地运行一样，交互式命令行输入`npm run start`就可以开始了

**Comment by 6s6t** [comment]
有一个问题
因为repl 会休眠，所以要用uptimerobot 来ping ,但是这需要有个网页，不知道怎么弄
