### ISSUE TITLE
如何设置多账户

### ISSUE THREAD

**Issue by 000redrum000** [shanmiteko/LotteryAutoScript#107]
### 描述Bug

    /**
     * 为防止环境变量过长, 请将多账号填在此处
     * 以大括号内容为模板依次复制(包含大括号),逗号分割
     */
    multiple_account_parm: [
       {
            COOKIE: "",
            NUMBER: 1,
            CLEAR: true,
            WAIT: 60 * 1000
        }，
       {
            COOKIE: "",
            NUMBER: 1,
            CLEAR: true,
            WAIT: 60 * 1000
        }
    ],

### 重现Bug

设置后跑不了

### 预期行为

怎么设置多账号

### 截图

![7187f7ab621b6efc5790d674dc058c3](https://user-images.githubusercontent.com/97618762/149180174-a0e81f70-e8fc-4b04-be23-d8b3d9d1b966.png)

### 运行日志

无

### 操作系统

window10

### 脚本版本

v2.4.5

**Comment by shanmiteko** [comment]
![Screenshot_20220113_120636.jpg](https://user-images.githubusercontent.com/87006121/149264217-18b67364-6d5a-4a07-8989-9fd11e83d3a0.jpg)
