### ISSUE TITLE
无法查询第二页私信，当我要使用check.bat 检查中奖情况时

### ISSUE THREAD

**Issue by zengxpmaster** [shanmiteko/LotteryAutoScript#11]
### 描述Bug

无法查询第二页私信

### 重现Bug

使用check.bat 检查中奖情况

### 预期行为

1. 不能检查第二页及以后的私信

2.网页上私信的小红点不能消去

3.无法及时了解中奖情况

### 截图

![9Q97UP37SLAE$8188X QIIN](https://user-images.githubusercontent.com/88627703/128639902-d4de12a3-3f38-46df-b836-3a51baa88ac5.jpg)

### 运行日志

[Mon Aug 09 2021 00:46:44 GMT+0800 (中国标准时间)] [Info] [main] [当前为第1个账号]
[Mon Aug 09 2021 00:46:44 GMT+0800 (中国标准时间)] [Info] [Cookie有效性检测] [成功登录UID:512799515]
[Mon Aug 09 2021 00:46:44 GMT+0800 (中国标准时间)] [Info] [中奖检测] [检查是否中奖]
[Mon Aug 09 2021 00:46:44 GMT+0800 (中国标准时间)] [Info] [获取未读@] [成功数量0]
[Mon Aug 09 2021 00:46:44 GMT+0800 (中国标准时间)] [Info] [获取未读私信] [成功已关注未读数: 2，未关注未读数0]
[Mon Aug 09 2021 00:46:44 GMT+0800 (中国标准时间)] [Info] [中奖检测] [<--正在检查己关注者的私信]
[Mon Aug 09 2021 00:46:45 GMT+0800 (中国标准时间)] [Info] [获取一页私信(20)] [成功第一页]
[Mon Aug 09 2021 00:46:45 GMT+0800 (中国标准时间)] [Info ][时延][1000ms]
[Mon Aug 09 2021 00:46:45 GMT+0800 (中国标准时间)] [Info] [私信已读] [成功-> talker_ id: 543749392 ]
[Mon Aug 09 2021 00:46:46 GMT+0800 (中国标准时间)] [Info I[时延][1000ms]
[Mon Aug 09 2021 00:46:46 GMT+0800 (中国标准时间)] [Info] [私信已读] [成功-> talker_ id: 31107135 ]
[Mon Aug 09 2021 00:46:47 GMT+0800 (中国标准时间)] [Info] [时延] [ 1000ms]
[Mon Aug 09 2021 00:46:47 GMT+0800 (中国标准时间)] **[error] [失败-> talker_ id: 221072795 ]**
[Mon Aug 09 2021 00:46:48 GMT+0800 (中国标准时间)] [Info] [中奖检测] [--> OK]
[Mon Aug 09 2021 00:46:48 GMT+0800 (中国标准时间)] [Info] [中奖检测][未中奖]
[Mon Aug 09 2021 00:46:48 GMT+0800 (中国标准时间)] [Info] [结束运行] [未设置休眼时间]
请按任意键继续

### 操作系统

Windows 7 版本 = "6.1.7601.24520"

### NodeJs版本

v13.9.0-x64

### 脚本版本

v2.0.4

### 其他

1.Windows源码运行

2.nodejs版本v13.9.0-x64是Windows7能安装的最新版本

**Comment by shanmiteko** [comment]
登录账号访问下[https://message.bilibili.com/#/whisper/mid221072795](https://message.bilibili.com/#/whisper/mid221072795)截图看看

**Comment by shanmiteko** [comment]
`git pull`拉取最新代码再试一下，日志会显示错误原因

**Comment by zengxpmaster** [comment]
![image](https://user-images.githubusercontent.com/88627703/128659535-3f75548d-3664-4206-9eb4-8e2893ded756.png)

**Comment by zengxpmaster** [comment]
我已经自行解决该问题；

方式：

将check.bat循环时间设置与**动态转发时间**相近，就不用查看第二页的私信。

但我还是无法消除红色字体的报错，

感谢。

**Comment by shanmiteko** [comment]
请提供一下最新版的报错信息

**Comment by shanmiteko** [comment]
> 登录账号访问下https://message.bilibili.com/#/whisper/mid221072795截图看看

是访问这个网址

**Comment by zengxpmaster** [comment]
![image](https://user-images.githubusercontent.com/88627703/128664874-f74e3caa-98d8-43d1-a2b3-f5c30293a3f5.png)

**Comment by shanmiteko** [comment]
这就很奇怪了，它根本就没给你发过私信，那为什么会check到它？

**Comment by zengxpmaster** [comment]
我无法运行v2.0.5版本，他将这样报错：

[Mon Aug 09 2021 14:08:20 GMT+0800 (中国标准时间)] [Info] [环境变量初始化] [成功加载env. js文件]
[Mon Aug 09 2021 14:08:20 GMT+0800 (中国标准时间)] [Info] [配置文件初始化] [成功加载my_ config. js文件]
( node : 6396 ) Unhandl edPromi seRe j ec tionWarning: TypeError: this.set is not a function
at init (C:\Users\Adminis trator\Downloads\Compressed\Lot teryAutoScript-main\lib\data\global_var.js:24:18)
at main (C:\Users\Administrator\Downloads\Compressed\Lot teryAutoScript-main\main. js:49:15)
at C:\Users\Adm inistr ator\Down1 oads\Compressed\Lot teryAutoScript-main\main.js: 124:27
at bject. <anonymous> (C: \Users\Adminis trator\Downloads\Compressed\LotteryAutoScript-main\main. js:139:3)
at Module. compile ( internal/modules/c js/loader.js:1151 :30)
at object. Module.. extensions. . js ( internal/modules/cjs/loader.js:1171 :10)
at Module . load ( internal/modules/cjs/loader.js:1000:32)
at Function . Module.. load ( internal /modules/cjs/loader.js: 899:14)
at Funct ion. execut eUserEntryPoint [as runMain] ( internal / modules/run_ main. js:71:12)
at internal/main/run main module. js:17:47
( node : 6396) Unhandl edPromi seRe jectionWarning Unhandled promise rejection. 
This error or iginated either by throwing inside of an async function without a catch
block，or by rejecting a promise which was not handled with .catchO，To termina
te the node process on unhandled promise rejection, use the CLI flag - - unhandle
d-rejectionsstrict (see https: / /nodejs. org/api/cli .html#cli unhandled rejectio
ns_ mode). (rejection id: 2)
( node :6396) [DEP0018] Deprecat ionWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled wi11 terminate the
Node. js process with a non-zero exit code .

**Comment by zengxpmaster** [comment]
我不知道为什么回check到，我是按照my_config.example.js严格填写my_config.js

**Comment by zengxpmaster** [comment]
当私信过多时，就无法check第二页及以后的，

因此

我延长了动态转发时间，解决因私信太多所带来的问题。
