### ISSUE TITLE
关于自动点赞功能

### ISSUE THREAD

**Issue by shw3310** [shanmiteko/LotteryAutoScript#111]
### 描述Bug

在My_config文件内只有关于使用点赞来进行查重功能的相关内容，但并没找到关于如何设置转发自动点赞相关的部分。

### 重现Bug

我翻了相关修改内容时，有人上传的截图有自动点赞成功内容，是2.4.7删除了该部分吗？

### 预期行为

无

### 运行日志

无

### 操作系统

WIN 10

### 脚本版本

2.4.7

### 其他

十分抱歉，我是这部分的新入门人士，连GITHUB都是第一次使用，如果给你添麻烦了，我只能说下次我会注意的。

**Comment by shanmiteko** [comment]
![Screenshot_20220119_223530.jpg](https://user-images.githubusercontent.com/87006121/150152002-077ed7c4-7c4a-4358-98b2-57e657c43de0.jpg)

选择“通过点赞判断”就会自动点赞

**Comment by shw3310** [comment]
原来如此。
