### ISSUE TITLE
在replit上遇到的问题

### ISSUE THREAD

**Issue by oorq** [shanmiteko/LotteryAutoScript#117]
### 描述

# [因为repl 会休眠，所以要用uptimerobot 来ping ,但是这需要有个网页，不知道怎么弄](https://github.com/shanmiteko/LotteryAutoScript/issues/106#issuecomment-1021004799)

**Comment by 1w5** [comment]
@shanmiteko 
## 他说的应该是这个
![image](https://user-images.githubusercontent.com/98456845/151159082-3782942f-96c5-4d39-adf4-5692f51341ca.png)
### 这样一个可以被外界访问的web
# 可以参考一下我正在部署的项目
#### https://github.com/qkqpttgf/OneManager-php#deploy-to-replit
