### ISSUE TITLE
希望能够在自动评论语句中加入up主昵称这一变量

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#118]
## 功能描述
希望在自动评论中增加一个变量，用于表示up主的昵称，由用户设置评论语时选择性插入,例如↓
```
        /**
         * 转发评语
         */
        relay: [ '好耶喜欢了','祝<up>早日百大!', '<up>最棒我吹爆', '这能没有我?','<up>粉丝越来越多'],

#此处以<up>代替表示这个变量
```
在下文中，为了方便大佬理解，我用<i>“用户名”</i>代指<b>up主在B站的账号名称（也是抽奖脚本获取到的抽奖信息当中存储的用户名）</b>，用<i>“nickname”</i>代指<b>我的JSON文件中经过人工优化过的up主的昵称</b>。

---

### ①可以优化评论语
可以让评论语更“智能”一点，舔一舔up主说不定就增加中奖概率了呢。别的脚本有的功能咱也想有，而且还能再做得更好一丢丢 :D
### ②比别的脚本语义更为自然
之所以没有直接全部使用脚本自行获取<i>用户名</i>，是因为可能造成语义不通更加尴尬。举个栗子↓
```
祝天选姬新年快乐，越来越可爱 √
祝拯救者天选B站官方账号新年快乐，越来越可爱 ×
```

所以我使用了人工排查的方式逐一爬取并修改了可能造成语义不通的up主<i>用户名</i>，并把优化后的<i>nickname</i>存储在一个JSON文件当中。
JSON文件存储在本地，由需要使用这一功能的群友自行下载并放在lottery程序的根目录。我也会不定期往里面添加数据并更新。

---

## 实现方式
1. 由lottery程序调用JSON，通过抽奖发起者UID查询up对应的<i>nickname</i>。
    ```
    JSON数据格式示例：
    {"401739957": "高漫手绘板", "602525524": "KBEAR魁宝耳机", "1131457022": "人民日报"}
    ```
2. 如果查询不到，则直接用抽奖信息中的<i>用户名</i>填充
3. 将最终的结果根据`<up>`这一变量加入评论语中，发布评论

**Comment by shanmiteko** [comment]
[提交用户名映射表](https://gitee.com/shanmite/lottery-notice/blob/master/update_uname_map.js)
