### ISSUE TITLE
#预约抽奖#tag包含着一般有(#预约抽奖##抽奖##转发抽奖#这三个),然后时间判断就不对,经常转发一些已结束的动态

### ISSUE THREAD

**Issue by poloiop** [shanmiteko/LotteryAutoScript#12]
### 描述

图片为最新转发的动态,应该在转发时判断是否有#预约抽奖#tag,做进一步判定

![image](https://user-images.githubusercontent.com/85426757/128887953-dc6c64bb-7b72-4da3-927d-ac0f21b5ca26.png)

**Comment by shanmiteko** [comment]
非官抽没有加时间判断
