### ISSUE TITLE
多账号设置的问题

### ISSUE THREAD

**Issue by Re1uy** [shanmiteko/LotteryAutoScript#120]
### 描述Bug

docker在运行完账号1后直接进入休眠，不执行账号2
![U2JTI{R{_{5$%X92D({%9ZS](https://user-images.githubusercontent.com/52073159/152639620-aaa0fd4c-f971-49d2-86f1-58358a74c9c5.png)
![2D2LKLGZ%UZ7$JW ) FQGAM](https://user-images.githubusercontent.com/52073159/152639627-0b2f4fed-175d-4e26-81ea-e7eca16d3b33.png)

### 重现Bug

未运行账号2

### 预期行为

应该运行

### 运行日志

![U2JTI{R{_{5$%X92D({%9ZS](https://user-images.githubusercontent.com/52073159/152639651-531363bb-5592-43c9-8b3e-7420cd64b4a1.png)

### 操作系统

docker

### NodeJs版本

v16.13.2

### 脚本版本

v2.4.10

**Comment by shanmiteko** [comment]
看注释

**Comment by Re1uy** [comment]
没懂
注释说
1.ENABLE_MULTIPLE_ACCOUNT 的值改为true已经改了；
2.multiple_account_parm的值也填了啊

**Comment by Re1uy** [comment]
哦我明白了

**Comment by shanmiteko** [comment]
number:1
...
number:2
