### ISSUE TITLE
大佬在吗，q群咋搜不到了

### ISSUE THREAD

**Issue by waerlp** [shanmiteko/LotteryAutoScript#126]
### 描述Bug

q群搜不到了，1078开头的这个

### 重现Bug

000

### 预期行为

000

### 运行日志

000

### 操作系统

10

### 脚本版本

1

**Comment by shanmiteko** [comment]
现在开了

**Comment by Camille672** [comment]
> 现在开了

大佬可以再开一下嘛。来晚了
