### ISSUE TITLE
开转发并评论的时候顺序改成先评论在转发

### ISSUE THREAD

**Issue by glowingtorch** [shanmiteko/LotteryAutoScript#128]
### 描述

现在转发加码抽奖评论会是这样 

新春赢好运，祝平安银行安总涨粉多多发展红火，中了大奖不取关[tv_斜眼笑]//@平安银行:#互动抽奖# #乐趣开年 福粒连连# 果粒总的对联活动真有意思！安总也来加个码~转评这条动态并【关注[@真果粒官方 ](https://space.bilibili.com/492777646) 和[@平安银行 ](https://space.bilibili.com/502893941)  】
3月5日抽取1位小平安送100元京东卡~#供电局福利#

应该只要留评论的这一句
新春赢好运，祝平安银行安总涨粉多多发展红火，中了大奖不取关[tv_斜眼笑]

**Comment by shanmiteko** [comment]
没必要吧

**Comment by ypw96** [comment]
> 没必要吧

/**
         * 转发并评论
         * - 评论内容与转发内容相同
         */
        is_repost_then_chat: true,
之前这个功能是为了解决评论时没有@的问题。（以前识别到需要@会@，但是只会转发@，评论没有）
但是打开这个功能后，加码的动态评论就会带上所有的内容，比如上面的举例。我觉得还是之前解决评论没有@的问题太过粗暴？

**Comment by glowingtorch** [comment]
> 没必要吧

也是，改成评论也@就行，不用转发评论一致
