### ISSUE TITLE
日志系统的请输入验证码是属于cookie失效需要重新登录吗？

### ISSUE THREAD

**Issue by qingzinai** [shanmiteko/LotteryAutoScript#131]
### 描述Bug

日志系统的请输入验证码是属于cookie失效需要重新登录吗？

### 重现Bug

正常运行提示需要输入验证码

### 预期行为

提示是否需要重新登录

### 运行日志

无

### 操作系统

windows10

### NodeJs版本

16.5.0

### 脚本版本

v2.5

**Comment by ypw96** [comment]
一般是评论环节，提示需要输入验证码。频繁出现的话，这种一般是风控了。等待几小时后再抽就是了。出现400和412报错同理

**Comment by qingzinai** [comment]
我发现现在很容易出这个提示基本挂一个小时必出然后运行10分钟以后基本都是账号异常的提示

**Comment by ypw96** [comment]
你应该考虑是不是你每个动态直接转发点赞评论间隔太短了？

**Comment by shanmiteko** [comment]
的确是因为操作太频繁被访问限制

**Comment by qingzinai** [comment]
那我把时间间隔变长点试试，感谢

**Comment by ypw96** [comment]
我觉得用默认的30秒够了

**Comment by qingzinai** [comment]
我就是用的默认的但是应该被风控了

**Comment by ypw96** [comment]
那就不清楚了。我22.出现概率比较小。

**Comment by shanmiteko** [comment]
Duplicate of #124
