### ISSUE TITLE
希望可以用消息提示现阶段运行到哪个账号

### ISSUE THREAD

**Issue by mirioer** [shanmiteko/LotteryAutoScript#132]
### 描述

这个功能我觉得有必要，当账号很多或者监视UID很多的时候，运行时就会产生很多运行日志，有时候从底部拖到顶部时都不一定会知道现在在运行哪个账号，而且我也不能一直挂着，再加上程序时不时就会出现异常，所以最后后面的账号就会很少机会参与抽奖（我现有账号9个，UID20多个就有这种情况了，我挂了半天最多才运行到第5个账号）
有这个功能，我下次运行的时候就可以方便调整一下账号顺序，而且要是某个账号运行时间较短我也可以看看是不是出现问题了，考虑到很多人都没有多账号，默认可以设置成关闭
（虽然有人可能会说你把前一半账号和后一半账号换一下位置就行了，话是这么说，不过账号再多一点就会有问题了）
（另外还有一个更好的假设，要是能同时运行多个账号就能更好的解决这个问题了）

**Comment by shanmiteko** [comment]
> > 同时跑多个账号风控的更快
> 
> 啊这，那这个请提供更多信息是什么意思？

具体怎么实现，要怎样的功能

**Comment by mirioer** [comment]
只能说大佬牛逼

**Comment by mirioer** [comment]
> > > 同时跑多个账号风控的更快
> > 
> > 
> > 啊这，那这个请提供更多信息是什么意思？
> 
> 具体怎么实现，要怎样的功能

大佬大佬，这个功能出bug了，消息推送和当前账号不一致，就是明明是账号一在抽奖，但是推送的是下一个账号的，不过这个bug出现之前出现过风控——“访问太频繁”，等了好一会继续抽就有这个bug了

**Comment by mirioer** [comment]
> > > 同时跑多个账号风控的更快
> > 
> > 
> > 啊这，那这个请提供更多信息是什么意思？
> 
> 具体怎么实现，要怎样的功能



> > > > 同时跑多个账号风控的更快
> > > 
> > > 
> > > 啊这，那这个请提供更多信息是什么意思？
> > 
> > 
> > 具体怎么实现，要怎样的功能
> 
> 大佬大佬，这个功能出bug了，消息推送和当前账号不一致，就是明明是账号一在抽奖，但是推送的是下一个账号的，不过这个bug出现之前出现过风控——“访问太频繁”，等了好一会继续抽就有这个bug了



> > > 同时跑多个账号风控的更快
> > 
> > 
> > 啊这，那这个请提供更多信息是什么意思？
> 
> 具体怎么实现，要怎样的功能

还有有风控的时候我调换了一下第一第二账号的顺序，再运行了一下，依然会有风控，然后就换回来等

**Comment by mirioer** [comment]
额，刚刚抽奖的时候又有风控了（不过我时延都设置到50秒了），提示要输入验证码，不过我没有理他，就这么放着，一会儿就又推送第三个账号开始抽奖，我翻了翻运行日志，发现还在运行第一个账号

**Comment by shanmiteko** [comment]
提供一下你的多账号设置

**Comment by mirioer** [comment]
[my_config.zip](https://github.com/shanmiteko/LotteryAutoScript/files/8230760/my_config.zip)

**Comment by mirioer** [comment]
> 提供一下你的多账号设置

好

**Comment by mirioer** [comment]
> 提供一下你的多账号设置

？

**Comment by shanmiteko** [comment]
> > 提供一下你的多账号设置
> 
> ？
这个`multiple_account_parm​`

**Comment by mirioer** [comment]
[env.zip](https://github.com/shanmiteko/LotteryAutoScript/files/8230789/env.zip)


> > > 提供一下你的多账号设置
> > 
> > 
> > ？
> 
> 这个`multiple_account_parm​`

**Comment by shanmiteko** [comment]
设置看起来没问题
