### ISSUE TITLE
出现闪退

### ISSUE THREAD

**Issue by y1ch3n** [shanmiteko/LotteryAutoScript#133]
### 描述Bug

无法从2.4.8更新
从github上下载2.5.1及2.5.2出现闪退，无法使用

### 重现Bug

正常操作，配置完成后，无法正常运行，出现闪退现象。

### 预期行为

未知

### 运行日志

无显示，仅跳出一瞬间界面

### 操作系统

win11

### NodeJs版本

v16.13.1

### 脚本版本

v2.5.2

**Comment by shanmiteko** [comment]
从命令行打开，提供一下报错信息
