### ISSUE TITLE
非官方抽奖添加点赞，收藏等功能

### ISSUE THREAD

**Issue by Pikarziur** [shanmiteko/LotteryAutoScript#137]
### 描述

很多非官方抽奖都是关注，评论，点赞，收藏，转发的

**Comment by shanmiteko** [comment]
能提供几个例子吗

**Comment by Pikarziur** [comment]
发现那些需要多种操作的都是视频抽奖，但是我已经停止了非官方抽奖，现在有点难找例子了
例如：
1.视频抽奖
https://www.bilibili.com/video/BV1eL4y1u78k（需要：关注。本视频浏览、点赞、投币、转评参与抽奖）
https://www.bilibili.com/video/BV1Ta4114789?spm_id_from=333.999.0.0（需要：关注+三连+评论）
PS：虽然我不知道他抽奖是否能检测那么多


2.动态抽奖
https://t.bilibili.com/641766584809947141?tab=2（需要：点赞+分享+关注）
https://t.bilibili.com/642944677173002290?tab=2 （关注 【转+评+赞】本动态）
PS：我不知道是否我不懂设置配置文件，好像没有找到点赞功能


3.双关注抽奖（还有一些是需要关注两号或以上的抽奖）
https://t.bilibili.com/642902891430936578?tab=2（关注@文石BOOX  和@Insta360  ，【转发+评论】本动态）
PS：不知道这些抽奖能否实现

**Comment by shanmiteko** [comment]
除了视频抽奖，其他的已经实现了

**Comment by Pikarziur** [comment]
请问一下，点赞设置叫什么，我转发抽奖的没有看到点赞原动态，在config搜点赞也只有写用点赞来检索是否重复点赞

**Comment by shanmiteko** [comment]
> 请问一下，点赞设置叫什么，我转发抽奖的没有看到点赞原动态，在config搜点赞也只有写用点赞来检索是否重复点赞

就是把这个设为0

**Comment by xiazhenhua** [comment]
/**
         * 检查是否重复转发
         * - 不检查 -1
         * - 通过是否点赞判断 0
         * - 检索本地dyids文件 1
         * - 通过是否点赞判断+检索本地dyids文件 2
         */
        check_if_duplicated: 1,
================================================
这个设置成0 会点赞吗，现在是不点赞的

**Comment by shanmiteko** [comment]
>  /**
>          * 检查是否重复转发
>          * - 不检查 -1
>          * - 通过是否点赞判断 0
>          * - 检索本地dyids文件 1
>          * - 通过是否点赞判断+检索本地dyids文件 2
>          */
>         check_if_duplicated: 1,
> ================================================
> 这个设置成0 会点赞吗，现在是不点赞的
> 
> 

提供一下错误日志
