### ISSUE TITLE
关于结尾转发随机动态判断的问题

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#139]
### 描述

当前在出现412错误或者其他错误导致未能获取到自己最后一页动态，导致判断出现问题，直接发随机动态。希望在没获取到动态时也能发随机动态。

**Comment by ypw96** [comment]
暂时没法提供错误日志，目前根据之前出现的情况分析，一般是同时运行了clean。获取动态详情出现412.导致在最后发送随机动态时需要获取自己最新一页动态来判断时候发送随机动态，但是动态获取412失败。然后被直接判断为不需要发送随机动态

**Comment by ypw96** [comment]
![@UOH2K844_VKD4%XFO(5` 8](https://user-images.githubusercontent.com/90349951/162712062-daa14cd0-cdb0-42eb-9256-6ccd8df39a67.jpg)
有时候会莫名判断已有非抽奖动态，有时候会报错停止下来

**Comment by ypw96** [comment]
根据群友提供的消息。是不是最后发送随机动态时检测是否已有非抽奖动态里的判定有问题，没有根据 key_words关键词判定。
或者能否给是否要发送随机动态的判定加个开关。

**Comment by shanmiteko** [comment]
设置里可以关闭转发
