### ISSUE TITLE
一个小问题 windows使用docker会找不到env.js

### ISSUE THREAD

**Issue by comspalpeen** [shanmiteko/LotteryAutoScript#141]
### 描述Bug

![image](https://user-images.githubusercontent.com/86298635/161409041-3e6ae344-c46d-42f0-8ce0-5bf2303e3c74.png)
会找不到文件

### 重现Bug

无

### 预期行为

无

### 运行日志

无

### 操作系统

windows 10

### 脚本版本

2.5.3

**Comment by shanmiteko** [comment]
请仔细阅读文档
