### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by y1ch3n** [shanmiteko/LotteryAutoScript#143]
### 描述Bug

更新显示 unable to verify the first certificate

### 重现Bug

点击update

### 预期行为

无法更新

### 运行日志

[请求失败]: unable to verify the first certificate
]

### 操作系统

win11

### NodeJs版本

v16.13.1

### 脚本版本

v2.5.2

**Comment by shanmiteko** [comment]
tls证书验证的问题，多试几次，或者手动下载
