### ISSUE TITLE
建议增加【每次运行转发N条就停止】功能

### ISSUE THREAD

**Issue by comspalpeen** [shanmiteko/LotteryAutoScript#144]
### 描述

因为转发太多容易被系统过滤 自定义开关和数量

**Comment by shanmiteko** [comment]
可以增大转发间隔

**Comment by huahuaword** [comment]
运行一个周期是多久，增加间隔会停止吗，感觉好像会一直运行下去，还有就是一天最多转发多少条呀100条会不会有点多了

**Comment by shanmiteko** [comment]
> 运行一个周期是多久，增加间隔会停止吗，感觉好像会一直运行下去，还有就是一天最多转发多少条呀100条会不会有点多了

都可以调整，具体参考[my_config.example.js](https://github.com/shanmiteko/LotteryAutoScript/blob/5b50611ffe81894ab356a99be91a5b1b258916a5/my_config.example.js)
