### ISSUE TITLE
求一个本地抽奖数据保存功能

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#145]
### 描述

希望在用户未使用云端抽奖数据接口的时候，能有一个本地的TXT文件存储爬取到的抽奖信息，并且可以设置使用第X个账号进行抽奖数据爬取，使用其他账号读取这个TXT中的抽奖数据，谢谢大佬

**Comment by jzcangshu** [comment]
仔细想想 这个功能可能对于多数人也没有很大需求 还是算了吧 orz

**Comment by shanmiteko** [comment]
不是有上传功能吗，你搭一个本地服务器接收一下不就行了
