### ISSUE TITLE
大佬能出一个arm版的docker镜像吗

### ISSUE THREAD

**Issue by 1399702039** [shanmiteko/LotteryAutoScript#148]
### 描述

感谢感谢

**Comment by shanmiteko** [comment]
在什么设备上运行

**Comment by 1399702039** [comment]
> 在什么设备上运行

在n1的openwrt上面

**Comment by shanmiteko** [comment]
不是有arm的包吗，直接用那个就好，或者安装运行环境node，npm用源码跑，没必要docker

**Comment by 1399702039** [comment]
> 不是有arm的包吗，直接用那个就好，或者安装运行环境node，npm用源码跑，没必要docker
![QQ图片20220413155655](https://user-images.githubusercontent.com/87305054/163128411-c3392370-626a-495c-91ac-85049f233596.png)
用包运行出现这个

**Comment by shanmiteko** [comment]
装的哪个包
走一个这个看看`uname -a`

**Comment by 1399702039** [comment]
> 装的哪个包 走一个这个看看`uname -a`
Linux N1 5.4.188 #1 SMP PREEMPT Fri Apr 1 11:45:58 CST 2022 aarch64 GNU/Linux

**Comment by 1399702039** [comment]
> > 装的哪个包 走一个这个看看`uname -a`
> > Linux N1 5.4.188 #1 SMP PREEMPT Fri Apr 1 11:45:58 CST 2022 aarch64 GNU/Linux

装的arm64那个

**Comment by shanmiteko** [comment]
用这个查一下是哪个发行版`lsb_release -a`然后用对应的包管理器下载npm，克隆源码后运行
