### ISSUE TITLE
docker使用 [未在当前目录下找到env.js文件 也可在环境变量中设置所需参数]

### ISSUE THREAD

**Issue by mathsishard233** [shanmiteko/LotteryAutoScript#15]
### 描述Bug

[Thu Aug 19 2021 17:24:54 GMT+0000 (Coordinated Universal Time)] [Warn] [环境变量初始化] [未在当前目录下找到env.js文件 也可在环境变量中设置所需参数]

### 重现Bug

./start.sh之后会显示未找到
但是按照readme里的步骤都修改创建了env.js和my_config.js

### 预期行为

。

### 截图

![K9WBU D_1FTB0{SVLE3M7X0](https://user-images.githubusercontent.com/57436570/130116117-779b0fd3-dcef-457b-b888-e75546b8d093.png)
![image](https://user-images.githubusercontent.com/57436570/130116331-520db308-218e-43f6-ad89-92a97d26da35.png)

### 运行日志

 MINGW64 /d/bilibili_lottery/LotteryAutoScript-main-1/LotteryAutoScript-main/script/docker/lottery
$ ./start.sh

> lottery-in-bili@3.0.0 start /lottery
> node main.js start

  _           _   _                   _____           _       _
 | |         | | | |                 / ____|         (_)     | |
 | |     ___ | |_| |_ ___ _ __ _   _| (___   ___ _ __ _ _ __ | |_
 | |    / _ \| __| __/ _ \ '__| | | |\___ \ / __| '__| | '_ \| __|
 | |___| (_) | |_| ||  __/ |  | |_| |____) | (__| |  | | |_) | |_
 |______\___/ \__|\__\___|_|   \__, |_____/ \___|_|  |_| .__/ \__|
                                __/ |                  | |
                               |___/                   |_|

                                              v1.9.7   by shanmite
[Thu Aug 19 2021 17:24:54 GMT+0000 (Coordinated Universal Time)] [Warn] [环境变量初始化] [未在当前目录下找到env.js文件 也可在环境变量中设置所需参数]

### 操作系统

win10 专业版

### 脚本版本

1.9.7

**Comment by shanmiteko** [comment]
使用docker不需要克隆代码仓库

```
$ curl -fsSL https://cdn.staticaly.com/gh/shanmiteko/LotteryAutoScript/main/script/docker/init.sh | sh
create lottery
create dyids/
create env.js
create my_config.js
docker pull shanmite/lottery_auto_docker
Docker version 20.10.0, build 7287ab3
Using default tag: latest
latest: Pulling from shanmite/lottery_auto_docker
Digest: sha256:4b9ea92165a90e9d9d3af4d7f0182972671322ad18da3fbaec11a0e43764b5af
Status: Image is up to date for shanmite/lottery_auto_docker:latest
docker.io/shanmite/lottery_auto_docker:latest
create start.sh
create check.sh
create clear.sh
$ cd lottery/
$ ls
check.sh      clear.sh      dyids         env.js        my_config.js  start.sh
$ ./check.sh

> lottery-auto-script@2.1.0 check /lottery
> node main.js check

  _           _   _                   _____           _       _
 | |         | | | |                 / ____|         (_)     | |
 | |     ___ | |_| |_ ___ _ __ _   _| (___   ___ _ __ _ _ __ | |_
 | |    / _ \| __| __/ _ \ '__| | | |\___ \ / __| '__| | '_ \| __|
 | |___| (_) | |_| ||  __/ |  | |_| |____) | (__| |  | | |_) | |_
 |______\___/ \__|\__\___|_|   \__, |_____/ \___|_|  |_| .__/ \__|
                                __/ |                  | |
                               |___/                   |_|

                                               Verison:   v2.1.0
                                               Written By shanmite
[2021-08-20T14:16:34.235Z] [Info] [环境变量初始化] [成功加载env.js文件]
[2021-08-20T14:16:34.237Z] [Info] [配置文件初始化] [成功加载my_config.js文件]
[2021-08-20T14:16:34.240Z] [Error] [错误] [
请查看README文件, 在env.js指定位置填入cookie
]
[2021-08-20T14:16:34.241Z] [Warn] [结束运行] [
5秒后自动退出
]
[2021-08-20T14:16:34.241Z] [Info] [时延] [5000ms]
```

在自动生成的目录里面修改里面修改配置文件

**Comment by shanmiteko** [comment]
windows运行建议直接用[nlts-win-x64-20210817.zip](https://github.com/shanmiteko/LotteryAutoScript/releases/download/v2.1.0/nlts-win-x64-20210817.zip)
