### ISSUE TITLE
还是之前提过的

### ISSUE THREAD

**Issue by ZYYStudyName** [shanmiteko/LotteryAutoScript#153]
### 描述

我之前发的那个图是被监视的账号转发的啊，我发现脚本自动转发的不是转发a，而是转发b，就是没有那个两个//只有一个转发动态然后后面就是动态b，跟转的只会是这样的：
![Screenshot_2022-06-03-10-59-34-551_tv danmaku bili](https://user-images.githubusercontent.com/105168030/171778015-c82eef85-ca48-4f98-a89a-7c81216e0941.jpg)
不会出现两个//我希望正确的应该是这样的：
![Screenshot_2022-06-03-08-15-37-965_tv danmaku bili](https://user-images.githubusercontent.com/105168030/171778097-9dbf19e8-9df2-4bbd-8c7d-5e775ef10901.jpg)

**Comment by shanmiteko** [comment]
Duplicate of #152
