### ISSUE TITLE
偷塔者模式参数

### ISSUE THREAD

**Issue by sikishana** [shanmiteko/LotteryAutoScript#154]
### 描述

sneaktower这个参数是用来打开偷塔者模式的，还是说设置偷塔者模式是否检查重复转发的

**Comment by shanmiteko** [comment]
https://github.com/shanmiteko/LotteryAutoScript/blob/main/lib/core/monitor.js#L313-L324

只是开启这个功能，且不检查重复，这个功能要配合特定格式的API接口使用
