### ISSUE TITLE
目前专栏有时候有预约抽奖，能否实现预约呢

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#155]
### 描述

检测到动态有预约抽奖的时候能否实现预约。

**Comment by shanmiteko** [comment]
有没有例子

**Comment by ypw96** [comment]
没例子，就是目前大锦鲤抽奖专栏里整合放进了预约抽奖的整理https://www.bilibili.com/read/cv17194163?from=search&spm_id_from=333.337.0.0，就和后面这个链接进去一样https://t.bilibili.com/673795865460080649?tab=2，下面有个预约。。F12点击预约时好像就调用了一个接口
这个好像就是预约的IDreserve_id: 733520。不做这个功能也行。毕竟咱们主要是转发动态抽奖
那么获取https://t.bilibili.com/673795865460080649?tab=2这个动态得到的内容，下面的预约有奖字眼识别的到吗？用屏蔽词可以屏蔽吗？

Request URL: https://api.vc.bilibili.com/dynamic_mix/v1/dynamic_mix/reserve_attach_card_button
Request Method: POST
Status Code: 200 
Remote Address: [240e:cf:9000:2::92]:443
Referrer Policy: no-referrer-when-downgrade
access-control-allow-credentials: true
access-control-allow-headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
access-control-allow-methods: GET,POST,OPTIONS
access-control-allow-origin: https://t.bilibili.com
bili-status-code: 0
cache-control: no-cache
content-encoding: br
content-type: application/json
cross-origin-resource-policy: cross-origin
date: Wed, 22 Jun 2022 11:16:31 GMT
expires: Wed, 22 Jun 2022 11:16:30 GMT
http-status-code: 200
l: v
server: swoole-http-server
set-cookie: l=v
status: 200
x-cache-webcdn: BYPASS from blzone04
x-trace-id: 4590669693037a19
:authority: api.vc.bilibili.com
:method: POST
:path: /dynamic_mix/v1/dynamic_mix/reserve_attach_card_button
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
content-length: 153
content-type: application/x-www-form-urlencoded
cookie: l=v; LIVE_BUVID=AUTO5216515105182960; buvid3=97EAD0C9-D40A-4555-A0AE-B88F0FD6AE3A148804infoc; _uuid=3F961EED-B763-7144-C2109-4D6A7AD9B710258204infoc; buvid4=A131AB96-2127-AF51-B556-B724EE9D45E372650-022012500-pVqSR3i+2VDNlgogRW8SyTzGEqQIFUBLQkGEnItW4yXkV81w0mF2jQ%3D%3D; fingerprint=a6df60d864fcfc6c75611f35996a1ad7; buvid_fp_plain=undefined; i-wanna-go-back=-1; b_ut=5; hit-dyn-v2=1; dy_spec_agreed=1; CURRENT_BLACKGAP=0; blackside_state=0; rpdid=0zbfVGaSAQ|OTkLlLjc|3u3|3w1NLUaK; nostalgia_conf=-1; CURRENT_QUALITY=112; fingerprint3=0d6727f7ba09abedb5c685599381a105; bsource=share_source_copy_link; sid=banc955a; bp_video_offset_414693729=674253266643583100; CURRENT_FNVAL=4048; b_lsid=F147A4310_1818ADBAA7F; innersign=0; _dfcaptcha=374cde6e43373613feba1be4dd533b0e; DedeUserID=414693729; DedeUserID__ckMd5=8633e1bf660b9bff; buvid_fp=a6df60d864fcfc6c75611f35996a1ad7; SESSDATA=1fd19188%2C1671448261%2Ccb095*61; bili_jct=e250abe45f87bc9d50786b9c309b8827; PVID=6; b_timer=%7B%22ffp%22%3A%7B%22333.967.fp.risk_97EAD0C9%22%3A%221816BEC6A7C%22%2C%22888.53980.fp.risk_97EAD0C9%22%3A%221816BECCB1D%22%2C%22888.47217.fp.risk_97EAD0C9%22%3A%221816BECDA35%22%2C%22888.45797.fp.risk_97EAD0C9%22%3A%221816BECFC08%22%2C%22444.62.fp.risk_97EAD0C9%22%3A%221816D317F8B%22%2C%22333.937.fp.risk_97EAD0C9%22%3A%221818B1F96C3%22%2C%22888.68165.fp.risk_97EAD0C9%22%3A%221818574A779%22%2C%22888.453.fp.risk_97EAD0C9%22%3A%221818574B00D%22%2C%22888.68182.fp.risk_97EAD0C9%22%3A%221817A727E70%22%2C%22888.27730.fp.risk_97EAD0C9%22%3A%221817A75460C%22%2C%22333.976.fp.risk_97EAD0C9%22%3A%221818B1B3158%22%2C%22888.67812.fp.risk_97EAD0C9%22%3A%221818A84E72A%22%2C%22333.880.fp.risk_97EAD0C9%22%3A%221818AF9DB48%22%2C%22333.794.fp.risk_97EAD0C9%22%3A%221818AFD9E9E%22%2C%22444.8.fp.risk_97EAD0C9%22%3A%221818AFFBEB5%22%2C%22333.866.fp.risk_97EAD0C9%22%3A%221818AFFD51B%22%2C%22333.1007.fp.risk_97EAD0C9%22%3A%221818B1B013B%22%2C%22333.337.fp.risk_97EAD0C9%22%3A%221818B1B13CE%22%2C%22333.42.fp.risk_97EAD0C9%22%3A%221818B1B4377%22%2C%22444.42.fp.risk_97EAD0C9%22%3A%221818B1F1CC3%22%7D%7D
origin: https://t.bilibili.com
referer: https://t.bilibili.com/673795865460080649?tab=2
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36
cur_btn_status: 1
dynamic_id: 673795865460080649
attach_card_type: reserve
reserve_total: 3013
reserve_id: 733520
spmid: 
csrf: e250abe45f87bc9d50786b9c309b8827

**Comment by ypw96** [comment]
目前只能获取到文本内容。
![image](https://user-images.githubusercontent.com/90349951/175367707-fdfe1bd5-8058-4074-a3ab-1a20105f5577.png)
目前专栏信息里有许多这类的预约抽奖。如上图，抽奖脚本目前只能获取到“速来预约！”，如果原文没有预约2字则没办法利用黑名单词屏蔽该动态，如何判断这个动态是否有官方预约抽奖，从而不抽这类动态。被钓鱼太难了

**Comment by wengshiquan** [comment]
需要设置什么吗，我现在是在监听的专栏关键词里设置了预约抽奖，和只转发官方抽奖
![Uploading QQ截图20220624150516.png…]()

**Comment by shanmiteko** [comment]
> 

这样就行
