### ISSUE TITLE
开始获取链接[object Object] 中的抽奖信息报错

### ISSUE THREAD

**Issue by wengshiquan** [shanmiteko/LotteryAutoScript#157]
### 描述Bug

开始获取链接[object Object] 中的抽奖信息报错
![QQ截图20220624152258](https://user-images.githubusercontent.com/43520089/175484592-5c5bd99b-aeda-41a9-b3b0-86aeb97f3076.png)

### 重现Bug

转发完一轮后报错

### 预期行为

。

### 运行日志

![QQ截图20220624152258](https://user-images.githubusercontent.com/43520089/175484762-10cda27c-44c5-44ae-943c-5df387d97368.png)

### 操作系统

Win10

### 脚本版本

v2.0.2

**Comment by shanmiteko** [comment]
链接填的什么

**Comment by wengshiquan** [comment]
![image](https://user-images.githubusercontent.com/43520089/175485767-6a90ca0f-7d20-4ee5-b817-8d1adc2aab7b.png)
是这个链接吗，默认是空的，我也不知道填什么

**Comment by wengshiquan** [comment]
文档里那个QQ群搜索不到
