### ISSUE TITLE
预约抽奖

### ISSUE THREAD

**Issue by lll666666** [shanmiteko/LotteryAutoScript#158]
### 描述

![image](https://user-images.githubusercontent.com/98231341/175866865-e9d1c60a-d726-44ed-a3ca-bea5e8cb5e62.png)
可能是参加太快了，建议增加间隔时间

**Comment by shanmiteko** [comment]
图片上传失败了。。。

**Comment by lll666666** [comment]
> 图片上传失败了。。。

![image](https://user-images.githubusercontent.com/98231341/175877047-3c64e123-49ab-4dbd-b3a7-de716529ef9b.png)

**Comment by shanmiteko** [comment]
这个错误可能是重复预约导致的
