### ISSUE TITLE
疑问，目前脚本会出现这种情况

### ISSUE THREAD

**Issue by Fitye** [shanmiteko/LotteryAutoScript#164]
### 描述Bug

![Snipaste_2022-07-14_22-19-48](https://user-images.githubusercontent.com/63393725/179004774-9d73eb15-1cac-43e5-a7ed-587056fe2c2d.png)

### 重现Bug

。

### 预期行为

。

### 运行日志

。

### 操作系统

Windows10

### 脚本版本

v2.5.8

**Comment by Fitye** [comment]
是被云控了么还是ip被墙了

**Comment by shanmiteko** [comment]
是被风控了

可以通过手动获取tagid然后填在设置里解决

**Comment by Fitye** [comment]
tagid具体的获取方式是什么

**Comment by shanmiteko** [comment]
点你的关注再点关注分区，链接里有tagid

**Comment by Fitye** [comment]
找到tigid了，填在设置里的具体哪个位置呢
