### ISSUE TITLE
程序在请求多次输入验证码时切换下一个账号

### ISSUE THREAD

**Issue by mirioer** [shanmiteko/LotteryAutoScript#167]
### 描述

我们都知道，一个账号在一次运行中多次转发抽奖后，就会出现风控，具体在日志中的表现就是需要输入验证码（如图）通过我的观察发现这种现象主要跟转发次数有关，就是说纵使你转发速度的间隔再慢（我之前设置了一分钟左右一条，是默认30秒的**两倍**时间）只要次数多了，照样还是会风控。只要出现了，这个账号的效率就会大打折扣。

（最近几天我拿我弟的新电脑来试了一下，程序是最新的，但也还是有这种现象）总的来说，**主要和单次运行时转发次数有关，次要和转发间隔有关**，与其他无关。

那么我觉得可以找一个方法来解决这个问题，只要验证码出现次数超过我们设定的值，那么就切换下一个账号继续抽奖（我现在也是这么做的，只不过是手动而已）

**新功能举例**：假设我在配置文件中设置了只要出现10次验证码信息，程序就会切换下一个账号抽奖，然后现在验证码出现了第10次，程序等待一会后，先是发送推送说“出现验证码次数过多，账号结束抽奖”，然后中断该账号切换下一个账号，然后再发推送。这个功能可以设置true和false来开启，然后再设置次数。
![QQ图片20220715203947](https://user-images.githubusercontent.com/88777965/179226081-24af0a51-2cc9-4a11-a1b8-cd25af12b3a3.png)

**Comment by shanmiteko** [comment]
访问限制应该是针对IP地址的（未测试），切换帐号但IP地址未变也许不会起作用

**Comment by mirioer** [comment]
> 一个替代方案：复制多份同时运行，分别连上代理IP

嗯。。。我觉得这个替代方案一般，感觉会有点麻烦，这个问题我认为可以等大佬你测试完IP地址对访问的影响后再考虑

**Comment by mirioer** [comment]
不过我想我平常出现这种现象都是先结束程序，然后更换一下账号，再启动程序。这么简单的一个过程可以使IP地址改变的话，是不是意味着IP地址的改变会比较简单？

**Comment by mirioer** [comment]
> > 不过我想我平常出现这种现象都是先结束程序，然后更换一下账号，再启动程序。这么简单的一个过程可以使IP地址改变的话，是不是意味着IP地址的改变会比较简单？
> 
> 怎么更换帐号的，如果这样操作可以避免验证码，就说明评论风控与IP无关和帐号有关

额，就是关掉程序，然后打开env.js，把多账号中放在第一个位置的账号剪切（或者说就是那个出现风控的账号），然后粘贴到多账号末尾，保存后再次运行程序
