### ISSUE TITLE
预约抽奖不关注up主是正常的吗

### ISSUE THREAD

**Issue by shadow6336** [shanmiteko/LotteryAutoScript#168]
### 描述Bug

预约抽奖不关注up主是正常的吗

### 重现Bug

预约抽奖不关注up主是正常的吗

### 预期行为

预约抽奖不关注up主是正常的吗

### 运行日志

无

### 操作系统

无

### 脚本版本

无

**Comment by shanmiteko** [comment]
没有要求关注

**Comment by shadow6336** [comment]
> 没有要求关注

好的，感谢大佬
