### ISSUE TITLE
评论区关闭时，正常运行到下一条动态

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#175]
### 描述Bug

目前转发评论遇到评论区关闭的情况,会直接停止脚本。希望能正常跳过该条，到下一条。

### 重现Bug

正常运行脚本，遇到评论区被关闭的动态。

### 预期行为

正常评论或者跳过被关闭评论的动态。

### 截图

![image](https://user-images.githubusercontent.com/90349951/184527294-212abb2c-7ca8-4a5c-a833-60f01dc3e9e5.png)

### 运行日志

1

### 操作系统

windows 7

### 脚本版本

v2.5.9

**Comment by shanmiteko** [comment]
![-786aefae20e21d16](https://user-images.githubusercontent.com/87006121/185787267-b3dba322-c92d-43ed-b5bb-2a982053a77a.png)
