### ISSUE TITLE
最近账号掉COOKIE很严重。希望检测一下原因

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#177]
### 描述

掉COOKIE很严重，不知道是同IP多号的问题，还是时间间隔的问题。或者是API太老的问题。

**Comment by mirioer** [comment]
掉cookie严重可能是之前更新的出现验证码切换下一账号的功能，详情请看#167的issues

**Comment by mirioer** [comment]
我发现掉cookie严重可能是因为有了#167的新功能后可以让程序持久的运行下去，一般一次运行最多是一天半，这样操作两个星期后就会开始掉cookie

**Comment by mirioer** [comment]
建议作者加一个选择程序运行循环次数的设置，比如从账号1运行到账号5是一次，自己可以根据情况设置多少次，因为我发现程序运行太久不仅会有掉cookie的问题，还有程序会闪退的问题，我曾经试过看看程序能运行多久，我一开就挂了两天，第三天就看到程序已经没掉了

**Comment by shanmiteko** [comment]
> 建议作者加一个选择程序运行循环次数的设置，比如我有五个账号，从账号1运行到账号5是一次，自己可以根据情况设置多少次，因为我发现程序运行太久不仅会有掉cookie的问题，还有程序会闪退的问题，我曾经试过看看程序能运行多久，我一开就挂了两天，第三天就看到程序已经没掉了

把时间调到一天，或者不使用内循环试试
https://github.com/shanmiteko/LotteryAutoScript/blob/664e33b3a608f42313acaad49949004d1baf2263/my_config.example.js#L179-L186

**Comment by shanmiteko** [comment]
> 建议作者加一个选择程序运行循环次数的设置，比如我有五个账号，从账号1运行到账号5是一次，自己可以根据情况设置多少次，因为我发现程序运行太久不仅会有掉cookie的问题，还有程序会闪退的问题，我曾经试过看看程序能运行多久，我一开就挂了两天，第三天就看到**程序已经没掉**了

最好能提供报错退出的日志

**Comment by ypw96** [comment]
> 掉cookie严重可能是之前更新的出现验证码切换下一账号的功能，详情请看 #167 的issues

个人感觉并不是，之前是出现验证码循环叠加等候时间，跳到下一个动态。要是还是验证码。继续循环。问题是我基本很少出验证码，或者一个号只出现1-2次，并不是所谓账号间隔的问题把。

**Comment by ypw96** [comment]
关闭问题，应该是B站的问题。
