### ISSUE TITLE
减少“账号未登录”情况下的尝试次数

### ISSUE THREAD

**Issue by congqianyzs** [shanmiteko/LotteryAutoScript#179]
### 描述

感觉掉号之后自动重试5次有点多

**Comment by shanmiteko** [comment]
有截图吗

**Comment by congqianyzs** [comment]
![1](https://user-images.githubusercontent.com/72326985/185778978-7087d15e-406d-43fa-a003-8425bedb9136.png)

**Comment by shanmiteko** [comment]
![-786aefae20e21d16](https://user-images.githubusercontent.com/87006121/185781270-3fb35741-8066-482e-a547-53415486c862.png)
