### ISSUE TITLE
偶尔获取不了专栏信息

### ISSUE THREAD

**Issue by wj988** [shanmiteko/LotteryAutoScript#181]
### 描述Bug

获取不了专栏信息

### 重现Bug

未进行操作，和正常一样，就出现了bug

### 预期行为

开始筛选为0

### 操作系统

win10

### 脚本版本

2.6

**Comment by wj988** [comment]
![QQ图片20220821131716](https://user-images.githubusercontent.com/77109640/185906393-c544ed2e-02c2-41c4-accf-a7a425e70cbc.jpg)

**Comment by wj988** [comment]
![QQ图片20220821131716](https://user-images.githubusercontent.com/77109640/185906502-3f59143c-1f6c-4f06-987f-fa2b6dabceea.jpg)

**Comment by wj988** [comment]
账号可以看到专栏信息，但获取不了专栏信息

**Comment by ypw96** [comment]
![image](https://user-images.githubusercontent.com/90349951/186354764-68585e14-c635-4f9c-8a62-a9bf419c789f.png)
好像专栏获取接口改了。一直412
本地访问的一个URL，可以看看，
https://api.bilibili.com/x/web-interface/search/type?__refresh__=true&_extra=&context=&page=1&page_size=20&order=totalrank&duration=&from_source=&from_spmid=333.337&platform=pc&highlight=1&single_column=0&keyword=%E5%BC%80%E5%A5%96%E4%B8%A8&category_id=0&search_type=article&preload=true&com2co=true
{code: 0, message: "0", ttl: 1,…}
code: 0
data: {seid: "7416885361558495323", page: 1, pagesize: 20, numResults: 199, numPages: 10,…}
cost_time: {params_check: "0.000483", illegal_handler: "0.013726", as_response_format: "0.003388",…}
egg_hit: 0
exp_list: {5506: true, 6601: true, 7700: true}
in_black_key: 0
in_white_key: 0
numPages: 10
numResults: 199
page: 1
pagesize: 20
result: [{pub_time: 1661263759, like: 346, title: "8月24-25日<em class="keyword">开奖丨</em>110个抽奖链接",…},…]
rqt_type: "search"
seid: "7416885361558495323"
show_column: 0
suggest_keyword: ""
message: "0"
ttl: 1

返回参
