### ISSUE TITLE
Http 412被拦截

### ISSUE THREAD

**Issue by jiahengzz** [shanmiteko/LotteryAutoScript#182]
### 描述Bug

出现412尝试重新请求中

### 重现Bug

运行一段时间后出现

### 预期行为

1

### 截图

![捕获](https://user-images.githubusercontent.com/87698055/185833520-4b4de3b3-d39a-4dce-ba4c-9469120d6cb8.JPG)

### 运行日志

0

### 操作系统

win10

### NodeJs版本

16.5

### 脚本版本

最新

**Comment by wj988** [comment]
补充：创建随机动态时出现412

**Comment by wj988** [comment]
不是风控

**Comment by wj988** [comment]
补充：创建随机动态时出现412

**Comment by wj988** [comment]
补充：创建随机动态时出现412

**Comment by shanmiteko** [comment]
> 目前获取推荐时的412有时候会这样。不知道是否正确。 ![image](https://user-images.githubusercontent.com/90349951/186124713-80f94448-5525-40ae-9f5b-6c57f5c40530.png)

Fixed 29bf439

**Comment by ypw96** [comment]
> > 目前获取推荐时的412有时候会这样。不知道是否正确。 ![image](https://user-images.githubusercontent.com/90349951/186124713-80f94448-5525-40ae-9f5b-6c57f5c40530.png)
> 
> Fixed [f75d2b6](https://github.com/shanmiteko/LotteryAutoScript/commit/f75d2b66c49b7ee88cc33a1ae665b2d4bd20e21b)

哦搞错了。这个412错误是获取当前用户最后的一页动态报错。不是获取推荐。
