### ISSUE TITLE
请求加入出现小错误后跳过该步骤，切换到下一个监视的用户，继续抽奖

### ISSUE THREAD

**Issue by mirioer** [shanmiteko/LotteryAutoScript#19]
### 描述

每次到一些用户uid就会出现需要验证码，或者评论失败，我觉得可以干脆让程序放弃掉这些用户，自动切换到下一个用户接着抽，不然每次抽到一半停下来，手动调整很麻烦，麻烦大佬了，实在难做可以考虑一下，必要的话可以打赏
![image](https://user-images.githubusercontent.com/88777965/132129707-c787c5e8-c9ec-482a-a16e-e53228bf5ec0.png)

**Comment by shanmiteko** [comment]
提示需要输入验证码，就是被风控了，可以降低操作频率，每两天运行一次都够了
