### ISSUE TITLE
运行时自动评论出现未知错误提示报错[12078]

### ISSUE THREAD

**Issue by LuluDeer** [shanmiteko/LotteryAutoScript#192]
### 描述Bug

- 在代码运行的过程中，评论的时候会出现未知错误导致无法评论，实际去网页端手动评论，发现并未出现风控或验证码，账号是可以正常转发和评论的，就是代码无法正常执行评论功能
- 这个问题仅出现在我的第二个账号当中，我的第一个账号是可以正常执行到结束的

### 重现Bug

1. 重新替换cookie
2. 间隔半天后再次运行代码
3. 查询动态后，开始转发评论时依然会报错

### 预期行为

脚本能正常查看专栏和TAG并查询是否转发，当对未转发的进行转发评论时会出现报错

### 截图

![image](https://user-images.githubusercontent.com/67789763/189517704-35abab36-523f-4263-9db9-e3252828a734.png)

### 运行日志

`[2022-09-11T15:50:54.790+08] [Info] [筛选动态] [筛选完毕(2)]
[2022-09-11T15:50:54.948+08] [Info] [获取粉丝数] [ok]
[2022-09-11T15:50:55.058+08] [Error] [自动评论] [
未知错误
{"code":12078,"message":"12078","ttl":1,"data":{"need_captcha":false,"url":"","need_captcha_v2":false,"url_v2":"","success_action":0,"success_toast":"","success_animation":"","rpid":0,"rpid_str":"","dialog":0,"dialog_str":"","root":0,"root_str":"","parent":0,"parent_str":"","reply":{"rpid":0,"oid":703886913053917267,"type":17,"mid":1091242425,"root":0,"parent":0,"dialog":0,"count":0,"rcount":0,"state":0,"fansgrade":0,"attr":0,"ctime":1662882655,"like":0,"action":0,"member":null,"content":{"message":"加油，冲冲冲","plat":0,"device":"","members":[],"jump_url":{},"max_line":0,"rich_text":null},"replies":null,"assist":0,"folder":{"has_folded":false,"is_folded":false,"rule":""},"up_action":{"like":false,"reply":false},"show_follow":false,"invisible":false,"reply_control":{}}}}
]`

### 操作系统

Windows 11 22H2

### NodeJs版本

v18.5.0

### 脚本版本

v2.6.1

**Comment by shanmiteko** [comment]
原因是这个 [关注UP主7天以上的人可发评论](https://t.bilibili.com/703886913053917267)
