### ISSUE TITLE
希望可以设置内循环次数

### ISSUE THREAD

**Issue by Camille672** [shanmiteko/LotteryAutoScript#195]
### 描述

当前代码如果设置了循环时间的话会一直循环下去直到手动关停或者它自己空转次数过多卡停
一般待机运行偷塔内容有更新的话只需要再循环一两次就好，因此希望可以设置下内循环次数，避免过多次空转，感谢

**Comment by shanmiteko** [comment]
建议用操作系统提供的定时任务功能
