### ISSUE TITLE
linux 运行npm run start 出现报错

### ISSUE THREAD

**Issue by mama2100** [shanmiteko/LotteryAutoScript#2]
linux 运行npm run start 出现报错，运行脚本后出现这样的情况是否由于npm与node版本导致的呢？
npm版本为7.20.0
node为v10.19.0

**Comment by shanmiteko** [comment]
请提供一下错误信息

**Comment by mama2100** [comment]
不好意思，刚刚图片没有上传成功，现在重新传上去试试
![捕获](https://user-images.githubusercontent.com/50139256/126119179-3e475037-4217-4a44-8481-2e5851cb3749.PNG)

**Comment by shanmiteko** [comment]
node能升到v11.0.0之后吗，之前版本不支持这个Array.prototype.flat()方法

**Comment by mama2100** [comment]
谢谢大佬解答

**Comment by shanmiteko** [comment]
建议用release里打包后的版本
