### ISSUE TITLE
有的账号掉cookie后就变成了实名认证

### ISSUE THREAD

**Issue by mirioer** [shanmiteko/LotteryAutoScript#204]
### 描述Bug

掉cookie后登录出现实名认证

### 重现Bug

掉cookie后登录出现实名认证

### 预期行为

掉cookie后登录出现实名认证

### 截图

![实名认证](https://user-images.githubusercontent.com/88777965/193972876-9accd79c-7c3f-4508-badd-ae384453c45f.jpg)

### 运行日志

无

### 操作系统

win10

### NodeJs版本

18.5.0

### 脚本版本

2.6.3

### 其他

我想了解一下这种情况的出现是脚本的原因还是什么别的其他原因（我记得没错的话这种情况在有直播预约抽奖之前是比较少出现的，8,9个号也就一个会有，现在好像频繁出现，我最近几个号都挂了），有没有什么方法解决，大佬你遇到这种情况一般是怎么解决的

**Comment by BlinkingStars** [comment]
一样高危账号了

**Comment by Huansheng1** [comment]
关注多了就是会这样，要抽奖避免不了该问题，要不每天只抽几个（调整配置），要不就实名，没有办法
