### ISSUE TITLE
清除动态时获取当前账号关注有误

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#207]
### 描述Bug

运行clean时，先获取用户关注时，获取的数量有误。

### 重现Bug

进行动态清理

### 预期行为

正常获取关注数

### 截图

![image](https://user-images.githubusercontent.com/90349951/196884821-dbfda036-6373-4f79-bc68-2fc5fdc38636.png)
该用户实际关注数
![image](https://user-images.githubusercontent.com/90349951/196884910-6741c936-b911-472c-86c6-4f80c07af493.png)

### 运行日志

无

### 操作系统

win7

### 脚本版本

2.6.3

**Comment by shanmiteko** [comment]
#208
