### ISSUE TITLE
预约抽奖间隔

### ISSUE THREAD

**Issue by XiangLong6** [shanmiteko/LotteryAutoScript#212]
### 描述

希望预约抽奖也能设置间隔时间，现在都是瞬间预约，希望可以像转发一样也出一个间隔时间的设置

**Comment by shanmiteko** [comment]
https://github.com/shanmiteko/LotteryAutoScript/blob/main/my_config.example.js#L236-L240

**Comment by XiangLong6** [comment]
没注意到，蟹蟹(˵¯͒〰¯͒˵)
