### ISSUE TITLE
清除已经开奖的   官方抽奖

### ISSUE THREAD

**Issue by Serroro4** [shanmiteko/LotteryAutoScript#213]
### 描述

清除已经开奖的   官方抽奖

**Comment by shanmiteko** [comment]
是否指的是清理动态功能

https://github.com/shanmiteko/LotteryAutoScript/blob/e0a8ce5b20ecaf71b511635d60e02fca2ff5ff24/package.json#L9

**Comment by Serroro4** [comment]
这个只能清理自定义日期之前的，清理开过奖的官方动态

**Comment by Huansheng1** [comment]
这个需求很难实现，因为不同主播的开奖方式不一，难以程序检测是否开奖

**Comment by Serroro4** [comment]
清理官方抽奖工具已开奖动态
