### ISSUE TITLE
中奖推送

### ISSUE THREAD

**Issue by XiangLong6** [shanmiteko/LotteryAutoScript#214]
### 描述

中奖推送好像不管什么内容被@就推送，希望@检测也可以像私信检测一样受关键词和屏蔽词影响~~

**Comment by XiangLong6** [comment]
![Screenshot_2022-11-04-11-09-38-345_com tencent mobileqq](https://user-images.githubusercontent.com/108725882/199876786-14b41577-6beb-4e17-a159-f6ee069315b6.jpg)
像这样，只要被@就推送了~~

**Comment by ypw96** [comment]
如果要加的话建议不配置就是默认和之前一样。啥@都推送。主要是@有时候会因为开奖数量多。只@没任何字，第一个@可能才有恭喜中奖之类的字。可能会漏。我其实希望弄个微信企业应用推送，QQ邮箱虽然方便，但是要一个个点进去看。

**Comment by shanmiteko** [comment]
> ![Screenshot_2022-11-04-11-09-38-345_com tencent mobileqq](https://user-images.githubusercontent.com/108725882/199876786-14b41577-6beb-4e17-a159-f6ee069315b6.jpg)
> 像这样，只要被@就推送了~~

这种直接拉黑就行
