### ISSUE TITLE
青龙运行无法手动停止

### ISSUE THREAD

**Issue by lll666666** [shanmiteko/LotteryAutoScript#222]
### 描述Bug

![image](https://user-images.githubusercontent.com/98231341/201448399-4a8b202b-cacd-45bb-aa90-53e152e838b9.png)
在运行中点击停止后脚本还在运行

### 重现Bug

点击停止后脚本还在运行

### 预期行为

点击停止后脚本停止运行

### 运行日志

![image](https://user-images.githubusercontent.com/98231341/201448560-56fe8ed2-5050-448f-87d3-5dc8fab046f4.png)
青龙日记显示停止后过一会发现还是在运行

### 操作系统

青龙v2.14.9

### 脚本版本

v2.6.8

**Comment by shanmiteko** [comment]
qinglong的问题，你可以试试禁用脚本
