### ISSUE TITLE
关注分区移动可关闭

### ISSUE THREAD

**Issue by shanmiteko** [shanmiteko/LotteryAutoScript#228]
https://github.com/shanmiteko/LotteryAutoScript/blob/7b5a1778ea1276cb894484599970c791347dbf59/lib/core/monitor.js#L610

**Comment by lll666666** [comment]
请问关闭移动分区是直接注释掉或删除这些代码吗？

else if (await bili.movePartition(u, this.tagid)) {
                    log.warn("抽奖信息", `dyid: ${dyid}, uid: ${u} tagid: ${this.tagid}`)
                    /* 3000系错误 */
                    status = 1001
                    return true
                }

**Comment by lll666666** [comment]
> https://github.com/shanmiteko/LotteryAutoScript/blob/7b5a1778ea1276cb894484599970c791347dbf59/lib/core/monitor.js#L610

请问关闭移动分区是直接注释掉或删除这些代码吗？

else if (await bili.movePartition(u, this.tagid)) {
log.warn("抽奖信息", dyid: ${dyid}, uid: ${u} tagid: ${this.tagid})
/* 3000系错误 */
status = 1001
return true
}

**Comment by shanmiteko** [comment]
> > https://github.com/shanmiteko/LotteryAutoScript/blob/7b5a1778ea1276cb894484599970c791347dbf59/lib/core/monitor.js#L610
> 
> 请问关闭移动分区是直接注释掉或删除这些代码吗？
> 
> else if (await bili.movePartition(u, this.tagid)) {
> log.warn("抽奖信息", dyid: ${dyid}, uid: ${u} tagid: ${this.tagid})
> /* 3000系错误 */
> status = 1001
> return true
> }

你看着改吧，之后会加一个开关
