### ISSUE TITLE
取消关注

### ISSUE THREAD

**Issue by XiangLong6** [shanmiteko/LotteryAutoScript#229]
### 描述

![mmexport1670944810739](https://user-images.githubusercontent.com/108725882/207374182-9ff3acb9-035d-4dbb-9640-2076597c5762.png)
1.1这里这个多少天内转发过的upuid可不可以存出来一个文本文件(我想通过网页插件反选这个列表取消关注)
1.2内置到插件内新增一个取消关注的模式，取消多少天内没转发过的up(抽奖分组)(因为之前关注少的时候防止风控只设置了删动态，现在这个模式已经删了动态当时又没取关的就取关不到了

2.1读取所有私信，记录私信人uid存到文本文件(通过网页插件反选取关掉没有关注自动回复的up)
2.2内置到插件内，新增一个只取关无自动回复up，在1.2的基础上再筛选一次，只取关不在私信up列表里的人

总结1.1和2.1是希望保存列表txt好手动操作，1.2和2.2是把对应的手动操作内置到插件配置中

**Comment by XiangLong6** [comment]
大佬可不可以把保存uid到txt先做出来🥺

**Comment by shanmiteko** [comment]
你可以先自己加上

**Comment by shanmiteko** [comment]
你这个需求没看懂，需要手动操作吗

**Comment by XiangLong6** [comment]
就是现在删动态取关不是有个保存uid防止误删吗，这个我想把这些防止误删的保存到txt中

**Comment by XiangLong6** [comment]
现在的取关逻辑是，保存误删名单(n天内有转发过的up)~删n天之外的动态~判断这条动态的up在不在误删名单~不在取关~在就不取关

这样会有个问题，取关的逻辑要先有个动态能删除才会去判断取不取关，之前如果设置的仅删动态，这样已经被删除了动态的up就不会去判断要不要取关，就会一直躺在关注列表里

**Comment by XiangLong6** [comment]
我想换另一套逻辑，删动态时候保存防误删名单~动态删完之后，统一过滤一遍抽奖分组中的所有up逐个比对，不在误删名单中的就取关

**Comment by XiangLong6** [comment]
另一个想法就是，读取所有私信记录有发私信的up进防误删名单，这样有自动回复的up就不会取关，就不会出现因为多次取关关注取消中奖资格的情况了

**Comment by XiangLong6** [comment]
私信防误删这个可以在配置中设置一个开关，这样需要用到的打开，不需要的关闭就好

**Comment by XiangLong6** [comment]
如果整个功能不好做的话，或者不值得做的话，希望可以把防止误删up名单保存成txt，这样后面的我可以配合关注管理器手动操作，不懂代码自己搞不来，辛苦大佬了🦀🦀
