### ISSUE TITLE
专栏转发如果超过半数已转发可自定义是否跳过此专栏

### ISSUE THREAD

**Issue by jkluio78** [shanmiteko/LotteryAutoScript#23]
### 描述

如题，如果在转发某个专栏时关注数已满，在清理关注后再转发此专栏的动态可能由于转发超过一半不再检索此专栏，希望能新增一个配置，专栏转发时如果已经转发超过半数的动态时仍然强制检索剩余动态

**Comment by shanmiteko** [comment]
删除本地dyid文件

**Comment by jkluio78** [comment]
直接删除的话不会重复转发那些已经转发过的动态吗？有些开奖的过滤条件就是重复转发的不算吧

**Comment by jkluio78** [comment]
那换个说法，能否在my_config增加一个配置选择是否进行专栏验重，如果可以的话我提交一个PR

**Comment by shanmiteko** [comment]
可以提

**Comment by shanmiteko** [comment]
脚本要兼容之前版本的配置文件
