### ISSUE TITLE
转发语跟随评论语

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#238]
### 描述

现在有热评功能，之前的一个功能是否考虑改一改，麻烦的话就算了
       /**
         * 转发并评论
         * - 评论内容与转发内容相同
         */
        is_repost_then_chat: false,
是否考虑改成转发语跟随评论语。

**Comment by shanmiteko** [comment]
最好的转发词就是“转发动态”，有的还有at人的需求

官抽不会看，非官抽只看评论

而且修改有点麻烦

**Comment by ypw96** [comment]
好吧，只是个别中奖要求提供动态截图，不知道会不会因为觉得评论看不到说动态没带@或者#领不到，等以后出现较多领不到情况时我再考虑再提出这个需求把。
