### ISSUE TITLE
抄热评功能优化

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#239]
### 描述

抄袭热评出现有@的情况下能替换成配置文件里的@的人吗？
另外遇到表情包多的直接换个热评，或者替换一下表情包？大于3个表情包换个热评，小于的直接去掉？

**Comment by ypw96** [comment]
超热评遇到包含发送热评的人的昵称换成自己的昵称，这个是否可以

**Comment by shanmiteko** [comment]
#239
