### ISSUE TITLE
关于预约抽奖

### ISSUE THREAD

**Issue by lll666666** [shanmiteko/LotteryAutoScript#241]
### 描述

![Screenshot_2023-01-26-13-41-54-669_tv danmaku bili](https://user-images.githubusercontent.com/98231341/214837540-97289ffd-c255-4619-8570-303ef5f6b253.jpg)
偶然在B站刷到的，如果脚本是通过请求参加后返回重复预约的话，有没有可能改成将预约过的记录到本地，在预约前先判断是否预约过了，看看能不能提高中奖率

**Comment by shanmiteko** [comment]
客服指的重复预约应该是反复开关，脚本只有开启预约，不会关闭，看看日志里有无关于预约的错误日志

**Comment by lll666666** [comment]
![image](https://user-images.githubusercontent.com/98231341/216235940-93f865ef-76d7-41ac-96bd-c6682b8cb195.png)
![image](https://user-images.githubusercontent.com/98231341/216235917-82cb9bbc-7a3f-4d18-a751-db209479393e.png)
https://t.bilibili.com/756597723922169971
这条动态确实是条预约抽奖动态，不知道为什么没识别出来，其他的大部分都能识别出，目前发现只有小部分识别不出。
下面的就识别出来了。
![image](https://user-images.githubusercontent.com/98231341/216235814-8ebf995f-7c23-4fc6-a469-5dcd1c12c28d.png)

**Comment by shanmiteko** [comment]
无法复现，展示不知道原因

**Comment by lll666666** [comment]
https://t.bilibili.com/757671014763069456
又发现一条动态识别不出的  奇奇怪怪
![image](https://user-images.githubusercontent.com/98231341/216489159-a0b24084-944b-493d-8fe6-7224be1e1196.png)

**Comment by shanmiteko** [comment]
开debug级别的日志看一下

**Comment by lll666666** [comment]
> 开debug级别的日志看一下

ok

**Comment by lll666666** [comment]
https://t.bilibili.com/757665847954112560
![image](https://user-images.githubusercontent.com/98231341/217404022-6e570c53-d206-472b-beb7-2bc33cf09bac.png)
青龙运行debug日记：
[2023-02-08T06:13:54.922+08] [Debug] [帐号1 正在筛选的动态信息] [
{
    "lottery_info_type": "article",
    "create_time": 1675246227,
    "is_liked": false,
    "uids": [
        504140200,
        null
    ],
    "uname": "软软riu",
    "ctrl": [
        {
            "data": "441666939",
            "length": 18,
            "location": 238,
            "type": 1
        },
        {
            "data": "473099203",
            "length": 7,
            "location": 256,
            "type": 1
        },
        {
            "data": "695870138",
            "length": 6,
            "location": 263,
            "type": 1
        }
    ],
    "dyid": "757665847954112560",
    "rid": "222727371",
    "chat_type": 11,
    "des": "❀软软出道一周年纪念回❀\n\n❀ 2.8日晩上21.00 ❀\n\n当日上舰福利\n❀舰长：弹弹乐➕钥匙扣➕明信片\n❀提督：舰礼➕18r立牌或正常立牌➕手写信➕粘土人\n❀总督：见过再想叭～\n\n每个UID限领一个捏\nios充值没有礼物哦～\n\n棉花糖地址指路\nhttps://www.tapeclub.net/uu/Y6MDSY/BYPCUVFL?share_to=14&uid=4315915\n多投点多投点孩子太缺啦\n\n转发加关注 抽奖一个131.4元红包\n麻烦各位老师帮我转发一下啦\n@虚拟区高级运营_Official @DD情报局 @DD日报 ",
    "type": 2
}
]
[2023-02-08T06:13:54.923+08] [Debug] [帐号1 筛选动态] [
{
    "real_uid": 504140200,
    "mIsFollowed": false,
    "oriIsFollowed": true,
    "realIsFollowed": false,
    "needAt": false,
    "needTopic": "",
    "type": 2,
    "isRelayDynamic": false,
    "key_words": [
        "[抽奖送揪]|福利",
         "[转关评粉]|参与"
    ],
    "has_key_words": true,
    "blockword": [
        "抽奖预告",
        "機器",
        "送我",
        "给up",
        "好人卡",
        "肺炎",
        "默哀",
        "致敬",
        "考公",
        "公考",
        "抽奖开奖",
        "公益",
        "优惠券",
        "脚本号",
        "抽奖号",
        "钓鱼",
        "红包封面",
        "今日话题",
        "回答正确",
        "立牌",
        "手写明信片",
        "写真",
        "DD日报",
        "舰长",
        "上舰",
    ],
    "isBlock": true,
    "isLottery": true,
    "isSendChat": true
}
]
[2023-02-08T06:13:54.923+08] [Info] [帐号1 筛选动态] [包含屏蔽词(https://t.bilibili.com/757665847954112560)]

这个还是老样子识别不出，

**Comment by lll666666** [comment]
https://t.bilibili.com/758395270840975442

这条动态昨天识别出来是预约了，今天又识别不出，感觉可以将预约过的动态的dyid记录在本地来避免这个问题


[2023-02-13T07:54:34.610+08] [Debug] [帐号1 正在筛选的动态信息] [
{
    "lottery_info_type": "article",
    "create_time": 1675416059,
    "is_liked": false,
    "uids": [
        1311851,
        null
    ],
    "uname": "某科学的上琴糖厂",
    "ctrl": [],
    "dyid": "758395270840975442",
    "reserve_id": "1298641",
    "reserve_lottery_text": "预约有奖：某科学的超电磁炮T官方画册*6份",
    "rid": "223089421",
    "chat_type": 11,
    "des": "新的一年我们还是只能这样抽奖，实在是抱歉啊[UP_1311851_吃瓜]\n过年期间一直在忙直啵跟拍视频的事，没来得及搞新年抽奖来着。这两天琴琴双萌王了，想看琴琴的人应该会多些，那连带新年一起给糖厂的粉丝抽个炮T的画册吧！也希望大家往后能继续关注某系列！同时也感谢各位一直以来对糖厂的支持！[UP_1311851_好耶][UP_1311851_哼哼]",
    "type": 2
}

[2023-02-14T07:51:51.072+08] [Debug] [帐号1 正在筛选的动态信息] [
{
    "lottery_info_type": "article",
    "create_time": 1675416059,
    "is_liked": false,
    "uids": [
        1311851,
        null
    ],
    "uname": "某科学的上琴糖厂",
    "ctrl": [],
    "dyid": "758395270840975442",
    "rid": "223089421",
    "chat_type": 11,
    "des": "新的一年我们还是只能这样抽奖，实在是抱歉啊[UP_1311851_吃瓜]\n过年期间一直在忙直啵跟拍视频的事，没来得及搞新年抽奖来着。这两天琴琴双萌王了，想看琴琴的人应该会多些，那连带新年一起给糖厂的粉丝抽个炮T的画册吧！也希望大家往后能继续关注某系列！同时也感谢各位一直以来对糖厂的支持！[UP_1311851_好耶][UP_1311851_哼哼]",
    "type": 2
}

**Comment by shanmiteko** [comment]
#224
