### ISSUE TITLE
不正常地转发了预约抽奖

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#244]
### 描述Bug

开启了预约抽奖，关闭了转发预约抽奖
却仍然转发并评论了预约抽奖动态

### 重现Bug

start.bat

### 预期行为

按照配置选项中不转发评论预约抽奖

### 截图

![B52AD5C0-ECBB-41DD-BA59-835CAAE575B8](https://user-images.githubusercontent.com/49329079/216781327-e44df05c-248a-447a-ac54-ba3e62b0771f.jpeg)
![D6F30039-D31E-49B0-B932-A1563EB5D2E5](https://user-images.githubusercontent.com/49329079/216781341-08e738de-3c4f-4977-9ae2-1ba8719ee407.jpeg)

### 运行日志

如图

### 操作系统

win10

### 脚本版本

2.7.3

**Comment by jzcangshu** [comment]
并且还关注了up主

**Comment by shanmiteko** [comment]
#241

**Comment by ypw96** [comment]
我的建议是确定下自己的确用的最新版。

**Comment by jzcangshu** [comment]
最近没有再出现了
