### ISSUE TITLE
抄热评时没有正确把其id换为自己id

### ISSUE THREAD

**Issue by glowingtorch** [shanmiteko/LotteryAutoScript#254]
### 描述Bug

如截图，抄热评没有把昵称换为自己的，是哪里还要设置吗

### 重现Bug

start

### 预期行为

预期评论为自己昵称

### 截图

![QQ图片20230216212631](https://user-images.githubusercontent.com/74662271/219377545-f4fa76ab-51a5-4955-a876-0cdbdccc6959.png)

### 运行日志

1

### 操作系统

win10

### NodeJs版本

2.7.5

### 脚本版本

2.7.5

**Comment by shanmiteko** [comment]
发这条评论的人昵称可能不是这个
