### ISSUE TITLE
获取开奖时间失败，就直接跳下一个账号了

### ISSUE THREAD

**Issue by tjxsnshui** [shanmiteko/LotteryAutoScript#255]
### 描述Bug

获取开奖时间失败，就直接跳下一个账号了

### 重现Bug

[2023-02-18T04:01:52.478+08] [Error] [帐号1 获取开奖信息] [
失败
{"code":-9999,"msg":"","message":"","data":{}}
]
[2023-02-18T04:01:52.479+08] [Info] [帐号1 抽奖] [本轮共处理5条,成功参与3条]
[2023-02-18T04:01:52.482+08] [Info] [帐号1 结束抽奖] [原因: 获取开奖时间失败]
[2023-02-18T04:01:52.482+08] [Info] [帐号1 时延] [1ms]
[2023-02-18T04:01:52.720+08] [Info] [帐号4 公告] [
最新版本: v2.7.6 可使用`lottery update`下载
 - QQ群: 1078777380 暗号: 32768
 - SteamChat: s.team/chat/co7CvrV3
 - TG: t.me/dynamic_lottery

### 预期行为

应该这样会好点
[2023-02-18T04:08:11.089+08] [Warn] [帐号1 自动重试] [
将在 1 分钟后再次尝试(1/6)
]
[2023-02-18T04:08:11.089+08] [Info] [帐号1 时延] [60000ms]

### 运行日志

[2023-02-18T04:01:52.478+08] [Error] [帐号1 获取开奖信息] [
失败
{"code":-9999,"msg":"","message":"","data":{}}
]
[2023-02-18T04:01:52.479+08] [Info] [帐号1 抽奖] [本轮共处理5条,成功参与3条]
[2023-02-18T04:01:52.482+08] [Info] [帐号1 结束抽奖] [原因: 获取开奖时间失败]
[2023-02-18T04:01:52.482+08] [Info] [帐号1 时延] [1ms]
[2023-02-18T04:01:52.720+08] [Info] [帐号4 公告] [
最新版本: v2.7.6 可使用`lottery update`下载
 - QQ群: 1078777380 暗号: 32768
 - SteamChat: s.team/chat/co7CvrV3
 - TG: t.me/dynamic_lottery

### 操作系统

win10

### 脚本版本

v2.7.6

**Comment by shanmiteko** [comment]
更新了吗

**Comment by tjxsnshui** [comment]
2.7.6版本




ii丶Fire艹灬永远
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shanmiteko/LotteryAutoScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 上午9:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shanmiteko/LotteryAutoScript] 获取开奖时间失败，就直接跳下一个账号了 (Issue #255)





 
更新了吗

**Comment by shanmiteko** [comment]
你打开软件确认一下

**Comment by tjxsnshui** [comment]
是最新版 转发失败or查询开奖时间失败就会跳到下一个号，评论失败就是60s重试。前面两个跳号应该也和评论失败60s重试才对






ii丶Fire艹灬永远
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shanmiteko/LotteryAutoScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 上午10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shanmiteko/LotteryAutoScript] 获取开奖时间失败，就直接跳下一个账号了 (Issue #255)





 
你打开软件确认一下

**Comment by shanmiteko** [comment]
重新打包了一个版本

https://ghproxy.com/https://github.com/shanmiteko/LotteryAutoScript/releases/download/v2.7.6/lottery-auto-script-node18-win-x64.zip
