### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by tjxsnshui** [shanmiteko/LotteryAutoScript#256]
### 描述

1.多号的时候，如果1234转完了，此时程序关掉了，那么1234需要重新检索，花费时间才能到5678.所以应该可以加个判断dyid的最后修改时间，可以直接从5开始转。
2.抄热评表情包的问题，没有表情包就会【很尬】。
3.官抽的问题，我试了下过滤粉丝数是不会作用于官方抽奖的动态上的，我设置了9千万粉丝，照样可以转发关注官方抽奖。但是屏蔽词会作用在官方抽奖上，我设置了’关注，转发‘这一类屏蔽词，看到了官方抽奖动态会被识别为屏蔽词动态。我觉得这些屏蔽uid，屏蔽词，粉丝数筛选，可以不作用在官方抽奖上。因为屏蔽也只是为了屏蔽非官方第三方钓鱼的行为。官方有就转发，不受屏蔽影响
4.今天看到了识别出up的这个：关注@联想未来探秘局 ，【点赞+转发+收藏】，并在评论区【最爱公主殿下+@本人用户名】，就有机会收到我们准备的惊喜大礼！，开了热评，没开评论跟随转发的，识别出了【最爱公主殿下+@本人用户名】并评论了。没开热评，开了评论跟随转发的，没有识别出来了，依旧是转发评论自己填的句子。不知道是热评的原因还是评论跟随转发的原因导致的识别出了up特定的句子。

**Comment by shanmiteko** [comment]
1. 时间过长可以分两个文件夹
2. 表情包评论可以用正则过滤，没有表情包也不影响
3. 屏蔽词可以使用正则("^[^互].*关注")只影响非官
4. 两个设置是冲突的

**Comment by ypw96** [comment]
> 1. 时间过长可以分两个文件夹
> 2. 表情包评论可以用正则过滤，没有表情包也不影响
> 3. 屏蔽词可以使用正则("^[^互].*关注")只影响非官
> 4. 两个设置是冲突的

屏蔽词只影响非官抽？粉丝过滤呢？是不是也只影响非官抽

**Comment by shanmiteko** [comment]
> > 1. 时间过长可以分两个文件夹
> > 2. 表情包评论可以用正则过滤，没有表情包也不影响
> > 3. 屏蔽词可以使用正则("^[^互].*关注")只影响非官
> > 4. 两个设置是冲突的
> 
> 屏蔽词只影响非官抽？粉丝过滤呢？是不是也只影响非官抽

用正则限制的只影响非官，本身都会影响

粉丝过滤只作用于非官

**Comment by tjxsnshui** [comment]
屏蔽词我测的是都影响，粉丝数没有影响到官抽


ii丶Fire艹灬永远
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shanmiteko/LotteryAutoScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月18日(星期六) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shanmiteko/LotteryAutoScript] 建议 (Issue #256)





   
时间过长可以分两个文件夹
 
表情包评论可以用正则过滤，没有表情包也不影响
 
屏蔽词可以使用正则("^[^互].*关注")只影响非官
 
两个设置是冲突的
   
屏蔽词只影响非官抽？粉丝过滤呢？是不是也只影响非官抽
