### ISSUE TITLE
希望增加新的推送Chanify

### ISSUE THREAD

**Issue by Ayers0** [shanmiteko/LotteryAutoScript#257]
### 描述

https://github.com/chanify/chanify
PC上也能使用这个推送

**Comment by shanmiteko** [comment]
考虑下已有的推送方式

https://github.com/easychen/pushdeer

**Comment by Ayers0** [comment]
pushdeer有bug，如果报文过长会出现翻页直接跳过那一条推送的问题
还有个bark如果报文过长也会出现报错无法推送，想看下Chanify会不会有以上两种情况

**Comment by shanmiteko** [comment]
试试企业微信bot？

**Comment by Ayers0** [comment]
那我先用pushdeer吧
