### ISSUE TITLE
开抄热评也能保持转发评论一致

### ISSUE THREAD

**Issue by glowingtorch** [shanmiteko/LotteryAutoScript#259]
### 描述

现在得关掉转发热评一致才能抄热评，应该是因为先转发再评论，能不能先抄热评，转发词跟评论保持一致，达到评论并转发的效果

**Comment by ypw96** [comment]
目前开奖很少见UP要求转发也是和评论一样。暂时问题不大。建议开启抄热评后，转发用语改成默认的“转发动态”
