### ISSUE TITLE
自定义dyids写入位置以实现多脚本共用

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#260]
### 描述

想要实现复制出来的多个脚本可以共用dyids，减少重复转发浪费的时间并且尽可能减少每次转发数量避免账号异常
（就是不知道如果多个脚本同时运行的时候会不会导致冲突，或许可以每个账号运行结束后统一写入？）

不喜欢用点赞判断重复的原因是一旦开启视频抽奖 点赞几乎百分百异常（没有模拟观看视频）

**Comment by shanmiteko** [comment]
复制一下不是更简单吗

**Comment by nizhenyu2022** [comment]
dyids能弄个httpapi的就好了，方便多文件夹跑。。复制有时候忘了也挺麻烦的。。。

**Comment by ypw96** [comment]
想所有文件夹的脚本用一个位置的目前不太可靠。没等待机制，你大概率是还得手动控制其他文件夹的启动时间

**Comment by lll666666** [comment]
直接用命令cp一下挺快的

**Comment by jzcangshu** [comment]
自行解决方案：写了个python脚本实现定时自动同步各个dyid
