### ISSUE TITLE
建议增加gotify推送

### ISSUE THREAD

**Issue by 1774517553** [shanmiteko/LotteryAutoScript#264]
### 描述

用其他推送感觉不是特别方便，建议增加gotify推送，能修改推送为一整条看，号多了再翻看记录的时候会显得十分麻烦。
![image](https://user-images.githubusercontent.com/82749728/222925378-29c6aa29-f5b7-48ab-afa7-3d1d3a0bec20.png)

**Comment by shanmiteko** [comment]
提供一下相关链接

**Comment by 1774517553** [comment]
> 

https://gotify.net/
