### ISSUE TITLE
判断专栏是否转发完毕

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#265]
### 描述

如题，在读取转发完一个专栏后使用点赞专栏的方式进行标记，比1/2比对更不容易出现误差且省时间

**Comment by lll666666** [comment]
可以加个已转发完专栏的id存入本地

**Comment by xiaoyiying** [comment]
可不可以做一个开关，是否开启1/2中止查看该专栏的功能，我可以接受时间长但想要更精确一点
