### ISSUE TITLE
屏蔽充电抽奖

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#266]
### 描述

如图 转发关注评论参与了充电抽奖 希望能过滤掉
![image](https://user-images.githubusercontent.com/49329079/222951120-d39c0c29-18a9-4d51-ad21-0f5542de7fcf.png)

**Comment by shanmiteko** [comment]
#244

**Comment by glowingtorch** [comment]
![image](https://user-images.githubusercontent.com/74662271/229260090-ae8aa6e4-4d21-45b8-99ed-aebd56269ce9.png)
版本2.7.6，屏蔽词有包月，还是会转
