### ISSUE TITLE
下载了以后配置好文件不知道怎么打开  script文件夹里没有启动程序

### ISSUE THREAD

**Issue by kinmokuseig** [shanmiteko/LotteryAutoScript#268]
### 描述

如题，然后群也进不去暗号不对，大佬我给你发好友申请了，能不能拉我一下，墨琰

**Comment by shanmiteko** [comment]
暗号是32768

**Comment by kinmokuseig** [comment]
收到，已经进群了，谢谢大佬-------- 原始邮件 --------发件人： shanmite ***@***.***>日期： 2023年3月11日周六 18:25收件人： shanmiteko/LotteryAutoScript ***@***.***>抄送： kinmokuseig ***@***.***>, Author ***@***.***>主    题： Re: [shanmiteko/LotteryAutoScript] 下载了以后配置好文件不知道怎么打开  script文件夹里没有启动程序 (Issue #268)
暗号是32768
