### ISSUE TITLE
增加企业微信应用推送， 以及反馈一些小BUG

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#27]
### 描述

目前**server**酱免费有限制，pushplus有时候打不开，想增加个企业微信应用推送的功能，目前有的推送是企业微信机器人的群消息
参考这个文档的接口：https://work.weixin.qq.com/api/doc/90001/90143/90372#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89
获取企业应用参数
https://note.youdao.com/ynoteshare/index.html?id=351e08a72378206f9dd64d2281e9b83b&type=note&_time=1631328844683
参考的养号库
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE

另外目前的一些小问题想反馈下。推送消息，内容有点拼接上有点小问题
如图
![Screenshot_2021-09-24-02-11-03-74](https://user-images.githubusercontent.com/90349951/134562024-f2a7269b-5b57-4c18-87b0-8735fb7f44d6.png)

以及在pushplus里没有回车用来分隔内容

**Comment by ypw96** [comment]
因为企业微信机器人的群消息，用微信插件是接收不到的，只能下载企业微信来接收消息，不太方便，所以向大佬提出这么一个需求。谢谢

**Comment by davidelectricfree** [comment]
企业微信有字符数限制，这个项目不是很推荐用企业微信通知

**Comment by shanmiteko** [comment]
建议用邮件推送方式
