### ISSUE TITLE
关于抄评论屏蔽词

### ISSUE THREAD

**Issue by lll666666** [shanmiteko/LotteryAutoScript#270]
### 描述

<img width="553" alt="image" src="https://user-images.githubusercontent.com/98231341/224869029-0a05f8d0-5336-4170-85df-557d9e99a40b.png">
 
这是不是因为我加了  [未定事件簿_   这个多个 _ 的原因，本想着以此来屏蔽有我没有表情包的评论。。。

**Comment by shanmiteko** [comment]
左括号用`\[`
