### ISSUE TITLE
从API提取抽奖信息可以改成先查询dyid文件后再进行查看是否点赞吗

### ISSUE THREAD

**Issue by Ayers0** [shanmiteko/LotteryAutoScript#276]
### 描述

![api](https://user-images.githubusercontent.com/117542293/228652653-0b0d95ab-dd7d-434a-868b-d6d2902c434d.png)
数据库的数据如果没有及时删除，如果多次运行，先筛选点赞就会跟之前的重复，会耗费大量时间。
如果先筛选dyid情况会不会好一点

**Comment by shanmiteko** [comment]
https://github.com/shanmiteko/LotteryAutoScript/blob/main/my_config.example.js#L113-L121

用方式1

**Comment by shanmiteko** [comment]
> 如果先筛选dyid情况会不会好一点

改起来比较麻烦
