### ISSUE TITLE
从专栏里获取的一些预约抽奖，但是没有预约，我看了是有评论和点赞过记录，说明这个动态还是识别了

### ISSUE THREAD

**Issue by xiaoyiying** [shanmiteko/LotteryAutoScript#288]
### 描述Bug

如题

### 重现Bug

如题

### 预期行为

希望能预约

### 运行日志

无

### 操作系统

linux

### 脚本版本

2.7.10

**Comment by lll666666** [comment]
而且不知道什么原因，已预约抽奖的动态在第二次扫动态时有时候识别不出预约抽奖，导致在第二次运行时即使设置了不转关预约抽奖还会转发，感觉可以添加个参加预约抽奖后动态的dyid保存到本地dyids文件中，设置了不转关预约抽奖后扫到预约动态也一样，感觉这样就可以避免了
