### ISSUE TITLE
是否推送中奖逻辑判断有误

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#292]
### 描述Bug

当有同一个用户的多条未读私信时，一条有中奖消息，一条有屏蔽词，会导致不发出通知，是否合乎逻辑。
另外是否会考虑改成未读的每条@，每条私信，每条回复单独的推送，比如收到了一条@信息，2条包含关键词的私信，1条包含关键词的回复，会推送4次（不过这样也得考虑调用推送通知的接口的次数会不会不够。）

### 重现Bug

发送2条私信给需要检测的账号，第一条发送中奖关键词，第二条发送屏蔽词

### 预期行为

正常推送中奖的那条消息

### 运行日志

无

### 操作系统

win 7

### 脚本版本

2.7.9

**Comment by shanmiteko** [comment]
调整关键词优先级即可
