### ISSUE TITLE
请求添加cloudflare workers部署方式

### ISSUE THREAD

**Issue by 888haobing** [shanmiteko/LotteryAutoScript#3]
cf 的workers貌似可以run  js 好像大部分node.js 都能实现。大佬有没有兴趣搞一下

**Comment by 888haobing** [comment]
还有win7可以用吗

**Comment by shanmiteko** [comment]
win7可以用

**Comment by 888haobing** [comment]
![image](https://user-images.githubusercontent.com/76923303/126484019-4a73e4ca-64a4-4498-8967-3f44cf930eed.png)
# 但是他说这个

**Comment by shanmiteko** [comment]
运行前输入这个`set NODE_SKIP_PLATFORM_CHECK=1`

**Comment by 888haobing** [comment]
那cloudflare workers上怎么用呢？

**Comment by shanmiteko** [comment]
类似云函数的东西吗，这个脚本要持久化存储数据，弄起来很麻烦。

**Comment by 888haobing** [comment]
持久化存储数据
这个简单，cloudflare workers 有KV空间1G可以用用来储存

**Comment by shanmiteko** [comment]
跑不了nodejs
