### ISSUE TITLE
建议推送前在一个文件夹中输出推送日志

### ISSUE THREAD

**Issue by spiritLHL** [shanmiteko/LotteryAutoScript#30]
### 描述

如题，建议运行时推送日志本地输出到一个文件夹中，并定期清除日志，比如说7天前的日志啥的

主要是大佬的推送日志输出我实在不知道怎么获取。。。只能想到最原始的用检索文件获取的方式

**Comment by shanmiteko** [comment]
日志写入文件
`./lottery check >> $(date -u +"%Y%m%d.log")`
然后就是文件检索，内容检索

**Comment by shanmiteko** [comment]
日志写入文件
`./lottery check >> $(date -u +"%Y%m%d.log")`
然后就是文件检索，内容检索

**Comment by shanmiteko** [comment]
可以用shell脚本来实现

**Comment by spiritLHL** [comment]
老问题，输出的话用./check.sh >> $(date -u +"%Y%m%d.log")这个如果设置shell脚本定时执行，原来的myconfig内部不设置check循环，每次运行会创建一个新容器，运行后会遗留有docker容器不删除，这我不知道如何通过代码删除，请问能否在myconfig设置中加一个是否输出推送日志选项，每次循环输出一个推送日志文件？
