### ISSUE TITLE
希望添加ocr_api_server的Docker镜像Arm64架构的支持

### ISSUE THREAD

**Issue by yhddx666** [shanmiteko/LotteryAutoScript#307]
### 描述

Docker镜像运行在Arm64架构的处理器上，shanmite/ocr_api_server此镜像无Arm64架构支持，希望作者可以添加。

**Comment by shanmiteko** [comment]
用的什么设备

**Comment by shanmiteko** [comment]
可以直接用源码运行

**Comment by yhddx666** [comment]
使用的设备是斐讯N1，自带python2.7环境，很遗憾安装依赖会报以下错误：
ERROR: Could not find a version that satisfies the requirement ddddocr>=1.3.1 (from versions: 1.0.6)
ERROR: No matching distribution found for ddddocr>=1.3.1
源码运行报错找不到py模块：
ModuleNotFoundError: No module named 'ddddocr'

然而此设备很难升级python版本

谢谢你的回复，我想应该换设备试试了
