### ISSUE TITLE
可以部署在ibmfunction上吗

### ISSUE THREAD

**Issue by oorq** [shanmiteko/LotteryAutoScript#31]
### 描述

https://cloud.ibm.com/functions/

**Comment by shanmiteko** [comment]
> FaaS是无状态的，无状态意味着**本地内存、磁盘里的数据无法被后续的操作所使用**。大部分的状态需要依赖于外部存储，比如数据库、网络存储等。

> 
FaaS的函数应当可以快速启动执行，并拥有短暂的生命周期。函数在有限的时间里启动并处理任务，并在返回执行结果后终止。如果它执行时间超过了某个阈值，也应该被终止。

这个项目并不适合用云函数运行（运行时间较长且有状态）

**Comment by shanmiteko** [comment]
当然是可以部署的，只是很麻烦
