### ISSUE TITLE
转发过程中提示 up主分区移动失败 然后直接跳到转随机动态那一项

### ISSUE THREAD

**Issue by Ikaros107** [shanmiteko/LotteryAutoScript#310]
### 描述Bug

转发过程中提示 up主分区移动失败 然后直接跳到转随机动态那一项
提示这个 [
up主分区移动失败
{"code":22105,"message":"请先公开关注后再添加分组","ttl":1}
]

### 重现Bug

正常打开 没有其他多余的操作 以防万一我还多试了几次，都提示这个问题

### 预期行为

提示 up分区移动失败后 剩下的抽奖就不进行了 直接跳到转发随机动态

### 截图

![屏幕截图 2023-08-24 000740](https://github.com/shanmiteko/LotteryAutoScript/assets/121148073/2066ac81-dbbc-4fc8-89cd-74714721e5a5)

### 运行日志

不好意思 不太懂上传什么

### 操作系统

windows10

### NodeJs版本

v18.17.1

### 脚本版本

v2.8.2

**Comment by shanmiteko** [comment]
设置里修改不移动分区
