### ISSUE TITLE
docker运行报错

### ISSUE THREAD

**Issue by 6uu1** [shanmiteko/LotteryAutoScript#316]
### 描述Bug

使用：
```
curl -fsSL https://cdn.staticaly.com/gh/shanmiteko/LotteryAutoScript/main/script/docker/init.sh | sudo sh
```

报错
······
sh: 5: Syntax error: "(" unexpected
(23) Failed writing body
·······

疑似语法错误？

### 重现Bug

使用：
```
curl -fsSL https://cdn.staticaly.com/gh/shanmiteko/LotteryAutoScript/main/script/docker/init.sh | sudo sh
```

### 预期行为

正常运行

### 运行日志

······
sh: 5: Syntax error: "(" unexpected
(23) Failed writing body
·······

### 操作系统

debian11

### 脚本版本

最新

**Comment by shanmiteko** [comment]
sh -> bash

**Comment by 6uu1** [comment]
> sh -> bash

感谢！
