### ISSUE TITLE
国内服务器显示curl: (28) Failed to connect to cdn.staticaly.com port 443: Connection timed out

### ISSUE THREAD

**Issue by 6uu1** [shanmiteko/LotteryAutoScript#317]
### 描述Bug

国内服务器显示curl: (28) Failed to connect to cdn.staticaly.com port 443: Connection timed out

### 重现Bug

运行docker安装脚本

### 预期行为

正常初始化

### 运行日志

`````
curl: (28) Failed to connect to cdn.staticaly.com port 443: Connection timed out
```````

### 操作系统

debian11

### 脚本版本

最新

**Comment by shanmiteko** [comment]
再看一眼文档
