### ISSUE TITLE
控制下txt文件跑完之后清空一下

### ISSUE THREAD

**Issue by ypw96** [shanmiteko/LotteryAutoScript#321]
### 描述

能否加个开关控制下是否打开清理下lottery_dyids下的文件，跑完所有之后清理。删除或者清空都行。感觉毕竟是自己收集数据。跑完了就清空，下次就不会浪费时间再跑了

**Comment by lll666666** [comment]
青龙的话自己改start.sh文件
最后加一行 (111.txt改成自己txt的地址就行)
> 111.txt

**Comment by lll666666** [comment]
青龙的话自己改start.sh文件
最后加一行 (111.txt改成自己txt的地址就行)
  > 111.txt

**Comment by lll666666** [comment]
青龙的话自己改start.sh文件
最后加一行 (111.txt改成自己txt的地址就行)
<img width="67" alt="image" src="https://github.com/shanmiteko/LotteryAutoScript/assets/98231341/82584ae2-c9aa-4749-9136-9b4d8f4cc54b">

**Comment by ypw96** [comment]
本地呢。

**Comment by ypw96** [comment]
> 青龙的话自己改start.sh文件 最后加一行 (111.txt改成自己txt的地址就行) <img alt="image" width="67" src="https://user-images.githubusercontent.com/98231341/267683389-82584ae2-c9aa-4749-9136-9b4d8f4cc54b.png">

本地呢

**Comment by lll666666** [comment]
> > 青龙的话自己改start.sh文件 最后加一行 (111.txt改成自己txt的地址就行) <img alt="image" width="67" src="https://user-images.githubusercontent.com/98231341/267683389-82584ae2-c9aa-4749-9136-9b4d8f4cc54b.png">
> 
> 本地呢

改bat文件加  type nul > "111.txt"

**Comment by ypw96** [comment]
> > > 青龙的话自己改start.sh文件 最后加一行 (111.txt改成自己txt的地址就行) <img alt="image" width="67" src="https://user-images.githubusercontent.com/98231341/267683389-82584ae2-c9aa-4749-9136-9b4d8f4cc54b.png">
> > 
> > 
> > 本地呢
> 
> 改bat文件加 type nul > "111.txt"

应该是没用的。我用的脚本内置循环，而不是定时器启动。
