### ISSUE TITLE
建议识别动态，若动态出现关键字、关键词、转发词等，则使用关键词来进行评论

### ISSUE THREAD

**Issue by xiaoyiying** [shanmiteko/LotteryAutoScript#324]
### 描述

如图:
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/90679240/b4ec32ff-341a-4ec2-8618-6a1316b4e023)

或者：
      1.在my_config设置一个字符串数组，比如comment_keyword:[‘关键字’, '关键词', '转发词']
      2.判断动态是否包含该数组的任意字符串
      3.如果有则截取关键字(配置里配的)后20个字符作为评论+chat评论

当然这个需求不是很重要，这种情况比较少
感谢作者大大

**Comment by shanmiteko** [comment]
可以用抄热评功能
