### ISSUE TITLE
如果有需要带话题的动态，开启抄热评之后，没有带话题评论

### ISSUE THREAD

**Issue by xiaoyiying** [shanmiteko/LotteryAutoScript#329]
### 描述Bug

如果有需要带话题的动态，开启抄热评之后，没有带话题评论

### 重现Bug

如果有需要带话题的动态，开启抄热评之后，没有带话题评论

### 预期行为

如果有需要带话题的动态，开启抄热评之后，没有带话题评论

### 运行日志

如果有需要带话题的动态，开启抄热评之后，没有带话题评论

### 操作系统

linux

### 脚本版本

最新

**Comment by ypw96** [comment]
之前我还以为是考虑到别人@了和加动态了。免得多加了。重复了。

**Comment by ypw96** [comment]
是否可以考虑成如果热评没有@和话题，内容识别到需要加@和热评然后再加上？
