### ISSUE TITLE
使用抄评论功能时先根据动态判断是否需要@本人用户名

### ISSUE THREAD

**Issue by Ayers0** [shanmiteko/LotteryAutoScript#331]
### 描述

![975B3472-91DA-4F22-A31F-C7CCDFAC8D4A](https://github.com/shanmiteko/LotteryAutoScript/assets/117542293/b65b2fc6-cbbe-4902-8e89-97c9dd4458d6)
目前发现未来探秘局这个up是经常发类似@本人用户名的抽奖
https://b23.tv/GdXuG8P

**Comment by ypw96** [comment]
很难根据动态文章识别到对应的需要@自己的需求，目前的抄热评是可以实现有当评论的内容有@并且@是当前热评的人的昵称时，会替换成自己的。所以问题暂时可以关闭了

**Comment by shanmiteko** [comment]
已有
