### ISSUE TITLE
有些账号复制出来的只是临时cookie，有效期就几天？

### ISSUE THREAD

**Issue by Nevidebla** [shanmiteko/LotteryAutoScript#338]
我目前10个账号，但是有几个账号基本上过2、3天就cookie失效。
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/40110f03-6f91-44cb-aba0-ee6c6efe59db)

我为了避免错过中奖通知，基本每天都会把所有账号挨个用浏览器登录进去看一眼私信和回复。（每个账号分别用的是不同的chrome本地账户，数据是独立的）
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/267484e2-0bfc-46d5-bcd7-dbdbd0c1aec5)

后来经过我的观察，发现了其中的共通点：
正常账号F12界面是这样的，会拼凑出一个B站logo，cookie也能使用挺久。
![Uploading image.png…]()

非正常账号F12界面没有logo，复制出来的cookie过2、3天就失效了。
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/b126de23-edc6-437f-abb6-c697753f1525)

### NodeJs版本

18.5.0

### 脚本版本

2.8.13

**Comment by sikishana** [comment]
大佬，你账号实名了吗

**Comment by Lyzd1** [comment]
大佬，现在账号大概怎么可以搞到啊？我的小号用了这个被bili提示高危，要实名是怎么回事？
