### ISSUE TITLE
q群怎么无了

### ISSUE THREAD

**Issue by T-lXl** [shanmiteko/LotteryAutoScript#339]
### 描述

一段时间没用了被踢出小礼盒那个群了再加怎么显示群没了

**Comment by lll666666** [comment]
> ### 描述
> 一段时间没用了被踢出小礼盒那个群了再加怎么显示群没了

解散了

**Comment by shanmiteko** [comment]
> > ### 描述
> > 一段时间没用了被踢出小礼盒那个群了再加怎么显示群没了
> 
> 解散了

没解散，变回500人群了

**Comment by Sakura9359** [comment]
群还会开放吗？
