### ISSUE TITLE
验证码程序已挂

### ISSUE THREAD

**Issue by piaoxue1** [shanmiteko/LotteryAutoScript#343]
### 描述Bug

验证码识别已失效。

### 重现Bug

无论是挂着验证码识别程序，还是在需要验证的时候再打开，都是一样不工作，验证码识别程序疯狂跳带有token的post信息。然后抽奖主程序一直是等待验证状态。之前能正常工作，前一段时间突然不行了，更新ddddocr后仍不能正常工作。

### 预期行为

主程序能接受到识别后的二维码

### 截图

![Snipaste_2024-01-13_19-56-55](https://github.com/shanmiteko/LotteryAutoScript/assets/58386584/16e48252-30fc-4124-84a4-0dd0d916db05)

### 运行日志

无

### 操作系统

windows11

### NodeJs版本

v18.14.2

### 脚本版本

v2.8.12

**Comment by piaoxue1** [comment]
已经在另一台win11，node18的环境下试过，同样的问题，因此排除是个人配置或环境问题。

**Comment by shanmiteko** [comment]
主程序截图看看

**Comment by piaoxue1** [comment]
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/58386584/68dc5c5e-680d-44e6-a969-f63ed6febcbc)

**Comment by piaoxue1** [comment]
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/58386584/9fa67812-7af3-4398-9c6e-202f512407df)
这次识别程序是和主程序一同开启的，无论是先开主程序，等到需要验证的时候再开识别程序。还是一同开启，现在识别程序都是每秒刷新一条这样的post，而主程序毫无反应，一直等待验证。跟账号也无关系，上次另一个账号也是同样的情况

**Comment by piaoxue1** [comment]
疑似接口变动

**Comment by xzlosats111** [comment]
我现在也是小于1秒刷新一条这样的post，在相当长时间后会返回2024-11-05 00:01:02.9005544 [W:onnxruntime:, execution_frame.cc:858 onnxruntime::ExecutionFrame::VerifyOutputSizes] Expected shape from model of {1,-1} does not match actual shape of {22,1,8210} for output 387
然后主程序尝试输入验证码发评论
整个流程是没问题的，但是ocr程序疯狂的刷新post且识别时间很长每次要近十分钟，这是正常的吗？

**Comment by xzlosats111** [comment]
后续，重新下载更新ocr程序即可解决
