### ISSUE TITLE
获取粉丝数时出现问题

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#345]
### 描述Bug

![C_6BAZI)4G8V`OJQ H2P6(A](https://github.com/shanmiteko/LotteryAutoScript/assets/49329079/56358a3d-3ff3-4d28-a05c-3b3ac9606722)

### 重现Bug

如图

### 预期行为

如图

### 运行日志

（窗口不小心关了 只有截图里的了）

### 操作系统

win server2019

### 脚本版本

2.8.13

**Comment by lll666666** [comment]
感觉可以将第一个账号获取到的up的粉丝数记录到lottery_info中，减少访问B站api次数
