### ISSUE TITLE
请求添加新的部署方式

### ISSUE THREAD

**Issue by 6oh** [shanmiteko/LotteryAutoScript#35]
### 描述

https://www.deta.sh/
这个可以跑node,还有base数据库和云储存，不用担心数据储存问题，而且速度不错。最重要的是免费，对于像我们这种没钱买服务器的穷苦人民来说太好了！！
# 另，作者大大，请你的快乐水到账了吗

**Comment by shanmiteko** [comment]
似乎没有（

**Comment by 6oh** [comment]
尴尬，我好像扫错了吗

**Comment by shanmiteko** [comment]
这个deta可以用吗，怎么登录不了

**Comment by shanmiteko** [comment]
> An execution times out after 10s. Contact us for an increase (up to 20 seconds).

有时间限制
