### ISSUE TITLE
中奖检测方式更新

### ISSUE THREAD

**Issue by piaoxue1** [shanmiteko/LotteryAutoScript#352]
### 描述

现在对方自动回复的消息会被自动打上“此条消息为自动回复”，可以直接排除掉这类信息，再根据关键词检测其他信息

**Comment by ypw96** [comment]
应该是指，私信现在会提示哪些为关注自动回复的消息，
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/90349951/f4512b23-9977-4922-8e16-b7d7ed50f288)
希望在判断关键词时，先默认排除这些自动回复的消息，这样就不用设置太多非关键词。
