### ISSUE TITLE
又不行了

### ISSUE THREAD

**Issue by Nevidebla** [shanmiteko/LotteryAutoScript#353]
### 描述Bug

昨天紧急修复之后，更新完了确实好了，但是今天又这样了。
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/5c64585e-1b6c-4216-80ca-c6854b51d76f)
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/12acf212-1b30-422e-997a-0552c05cc26c)

### 重现Bug

1

### 预期行为

1

### 运行日志

1

### 操作系统

Win10

### 脚本版本

v2.8.14.2 Latest

**Comment by shanmiteko** [comment]
duplicate #349
