### ISSUE TITLE
中奖检测无效

### ISSUE THREAD

**Issue by Nevidebla** [shanmiteko/LotteryAutoScript#358]
### 描述

关键词是包含了的。
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/d91959bb-755a-4a02-b083-149a1a0d715d)
如下所示，这条中奖私信就没通知我
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/1382f0a5-326a-4fbd-ae86-de92843ccf8c)
并且被@之后也是没有检测出来
推送的信道是没问题的，刚才有个账号cookie掉了，微信上就收到推送了。

**Comment by ypw96** [comment]
建议让其他账号复制相同的内容发送给自己然后点中奖推送测试观看日志。有时候可能因为网络问题导致没推送上。先测试是软件问题还是其他问题。
