### ISSUE TITLE
新版本仍旧监控uid报错。

### ISSUE THREAD

**Issue by piaoxue1** [shanmiteko/LotteryAutoScript#366]
### 描述Bug

上次issue提到过，不再赘述。

### 重现Bug

，

### 预期行为

，

### 截图

，

### 运行日志

，

### 操作系统

，

### NodeJs版本

，

### 脚本版本

，

**Comment by Lyzd1** [comment]
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/162241377/e13ea9cc-a690-44b9-8727-41a0c59480c3)
我这里试了试，监控uid没有报错。

**Comment by shanmiteko** [comment]
#373
