### ISSUE TITLE
v2.8.15版本，仍然读取动态出错

### ISSUE THREAD

**Issue by Nevidebla** [shanmiteko/LotteryAutoScript#367]
### 描述Bug

![image](https://github.com/shanmiteko/LotteryAutoScript/assets/54260027/d4255bc2-e9b6-4da6-b90c-61396de7d6c4)

### 重现Bug

1

### 预期行为

1

### 运行日志

1

### 操作系统

Win10

### 脚本版本

v2.8.15

**Comment by shanmiteko** [comment]
#373
