### ISSUE TITLE
求大佬增加每次check循环输出一个推送的日志文件

### ISSUE THREAD

**Issue by spiritLHL** [shanmiteko/LotteryAutoScript#37]
### 描述

承接之前的建议

[https://github.com/shanmiteko/LotteryAutoScript/issues/30](https://github.com/shanmiteko/LotteryAutoScript/issues/30)

输出的话用

```bash
./check.sh >> $(date -u +"%Y%m%d.log")
```

这个如果设置shell脚本定时执行，原来的myconfig内部不设置check循环，每次运行会创建一个新容器，运行结束后会遗留有docker容器不会自动删除，每循环一次执行这个命令就多一个容器，这我不知道如何通过代码删除遗留容器

请问能否在设置中加一个是否输出推送日志选项，每次循环输出一个推送日志文件？

提前谢谢大佬回复

**Comment by spiritLHL** [comment]
源码执行有点伤，还是希望增加一个这样的功能

**Comment by shanmiteko** [comment]
只要check的？

**Comment by spiritLHL** [comment]
> 
> 
> 只要check的？

对
