### ISSUE TITLE
自动抓取评论问题

### ISSUE THREAD

**Issue by abuuukk** [shanmiteko/LotteryAutoScript#383]
### 描述

1.现在评论抓取是不是有bug，貌似不是找的热评，而是按时间顺序排序的当页几条内的随机评论
2.为了避免偷评论偷到无意义的，我设置了二三十个屏蔽词，屏蔽那些无意义的评论，但是手动检查发现，参与的抽奖有时候只会点赞分享不会评论，是不是屏蔽了当页检测的所有评论导致的，是因为检测复制热评的范围太小了?
3.能不能实现优先复制带#的评论，因为大部分需要准确评论的是要求带话题的

**Comment by shanmiteko** [comment]
发送失败了
