### ISSUE TITLE
验证码识别shanmite/ocr_api_server获取不到镜像

### ISSUE THREAD

**Issue by yang7758258** [shanmiteko/LotteryAutoScript#388]
### 描述Bug

shanmite/ocr_api_server
提示不存在，docker hub 也搜不到

### 重现Bug

无

### 预期行为

无

### 截图

![image](https://github.com/shanmiteko/LotteryAutoScript/assets/43715693/67cd6902-a0d1-4ac2-bbae-19b9ab01f176)

### 运行日志

Images: pulling shanmite/ocr_api_server:latest... latest: Pulling from shanmite/ocr_api_server code:200 no matching manifest for linux/arm64/v8 in the manifest list entries

### 操作系统

docker

### NodeJs版本

v20.12.1

### 脚本版本

2.02

### 其他

添加一下镜像吧

**Comment by shanmiteko** [comment]
手机docker？

**Comment by shanmiteko** [comment]
加上了
