### ISSUE TITLE
账号没有转发或预约动作

### ISSUE THREAD

**Issue by xzlosats111** [shanmiteko/LotteryAutoScript#389]
### 描述Bug

按教程设置后没程序正常运行，但是登录账户查看没有任何自动转发关注预约动作，不知自己设置有什么问题

### 重现Bug

配置文件如下
[my_config.js.txt](https://github.com/shanmiteko/LotteryAutoScript/files/15217932/my_config.js.txt)
![2024-05-06_153309](https://github.com/shanmiteko/LotteryAutoScript/assets/126597684/2f2c469f-f98f-4d29-818c-b6722c01eb24)

### 预期行为

自动转发预约

### 截图

![2024-05-06_152621](https://github.com/shanmiteko/LotteryAutoScript/assets/126597684/4ce92b45-5ae9-4a02-ad81-3bd8c038f0ad)

### 运行日志

为空

### 操作系统

Windows10

### NodeJs版本

18

### 脚本版本

v2.9.0

**Comment by xzlosats111** [comment]
补充，运行一段时间后发现是没有预约，但是有转发，那么问题不大
此外，我如果要监听你的工具人老公的专栏，按照关键词这样设置可以正常使用吗？

**Comment by shanmiteko** [comment]
看脚本日志就知道了
