### ISSUE TITLE
start时出现的错误TypeError: Cannot read property 'desc' of undefined

### ISSUE THREAD

**Issue by wulifuji** [shanmiteko/LotteryAutoScript#39]
### 描述Bug

报错跳出

### 重现Bug

更新后改配置文件，运行

### 预期行为

预期正常

### 截图

![image](https://user-images.githubusercontent.com/61496038/136139140-d60fa23f-4a93-408f-849c-55b7d51b0cbb.png)

### 运行日志

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError: Cannot read property 'desc' of undefined
    at parseDynamicCard (C:\snapshot\LotteryAutoScript\lib\core\searcher.js)
    at C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js
    at async C:\snapshot\LotteryAutoScript\lib\core\searcher.js

### 操作系统

win10 21H1

### NodeJs版本

16.5.0

### 脚本版本

2.2.0

### 其他

可能是个例，但请检查

**Comment by shanmiteko** [comment]
GET https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/get_dynamic_detail?dynamic_id=560553323018335682

{"code":0,"msg":"","message":"","data":{"_gt_":0}}
