### ISSUE TITLE
412请求被拦截是风控了吗

### ISSUE THREAD

**Issue by joker357** [shanmiteko/LotteryAutoScript#390]
### 描述Bug

每次运行频繁出现，不止一个账号这样，是不是运行频率过高导致的

### 重现Bug

正常运行，运行次数是每天一次

### 预期行为

脚本还会运行，但是之后又会重现这个错误

### 截图

![image](https://github.com/shanmiteko/LotteryAutoScript/assets/42162775/1363d089-02f4-42e7-af6b-1b9767e89011)

### 运行日志

SyntaxError: Unexpected token '响', "[响应错误]HTTP状"... is not valid JSON
[响应错误]HTTP状态码: 412 响应数据:
{"code":-412,"message":"请求被拦截","ttl":1,"data":null}
]
[2024-05-06T10:00:49.395+08] [Warn] [帐号1 获取一个动态的细节] [
获取动态数据出错:
[响应错误]HTTP状态码: 412 响应数据:
{"code":-412,"message":"请求被拦截","ttl":1,"data":null}
]
[2024-05-06T10:00:49.395+08] [Warn] [帐号1 获取一个动态的细节] [
切换线路(1/2)
]
[2024-05-06T10:00:49.540+08] [Warn] [帐号1 获取一个动态的细节] [
获取动态数据出错:
{"code":4100001,"message":"参数错误","ttl":1,"data":null}
]
[2024-05-06T10:00:49.541+08] [Warn] [帐号1 获取一个动态的细节] [
切换线路(2/2)
]
[2024-05-06T10:00:49.599+08] [Error] [帐号1 json解析] [
SyntaxError: Unexpected token '响', "[响应错误]HTTP状"... is not valid JSON
[响应错误]HTTP状态码: 412 响应数据:

### 操作系统

青龙面板

### NodeJs版本

20.12.2

### 脚本版本

2.9.0

**Comment by shanmiteko** [comment]
增大时延
