### ISSUE TITLE
ocr_api_server验证码服务启动之后在lottery中该如何配置

### ISSUE THREAD

**Issue by amadeus5201** [shanmiteko/LotteryAutoScript#395]
### 描述

看到设置里面有ocr_api_server，启动之后该如何配置到lottery中

**Comment by shanmiteko** [comment]
[详见文档](https://github.com/shanmiteko/LotteryAutoScript/blob/main/doc/chat_captcha_orc.md)

**Comment by shanmiteko** [comment]
启动了就可以

**Comment by amadeus5201** [comment]
我是在青龙里面使用的， 青龙面板是docker容器，ocr_api_server是个docker容器， 没办法直接使用

**Comment by shanmiteko** [comment]
可以用，端口映射出来

**Comment by amadeus5201** [comment]
> 可以用，端口映射出来

ip该如何配置。

**Comment by shanmiteko** [comment]
> > 可以用，端口映射出来
> 
> ip该如何配置。

我加一个设置

**Comment by amadeus5201** [comment]
谢谢谢谢！
