### ISSUE TITLE
评论验证码识别时卡住

### ISSUE THREAD

**Issue by XiaoZhiQ-Q** [shanmiteko/LotteryAutoScript#398]
### 描述Bug

评论验证码识别时卡住   出现识别验证码 然后不识别后 就会卡住  一开始是识别的 识别了一段时间后 就卡在识别了 一直没执行

### 重现Bug

填了内容 然后识别了一段时间 就出现卡住的情况

### 预期行为

识别验证码

### 截图

![image](https://github.com/shanmiteko/LotteryAutoScript/assets/84890346/1ec79013-9d96-42f2-b608-b2ca694c8dd6)

### 运行日志

![Uploading image.png…]()

### 操作系统

linux 青龙

### 脚本版本

2.711

### 其他

1

**Comment by XiaoZhiQ-Q** [comment]
![image](https://github.com/shanmiteko/LotteryAutoScript/assets/84890346/4f3162d1-147d-4148-9edb-0be49f4b80f9)
不清楚什么原因 换了两个服务器 一个国内一个国外 都搭建识别 都会卡住

**Comment by xdchm0719** [comment]
我也会卡住，docker日志一直在刷
![}VD~(DF21D OO8{U%4 `U{G](https://github.com/user-attachments/assets/131c65d4-3035-4fc1-acc2-79330276072e)
麻烦修复一下

**Comment by shanmiteko** [comment]
已修复，重新拉一下OCR镜像即可
