### ISSUE TITLE
请求添加otketo部署方式

### ISSUE THREAD

**Issue by 888haobing** [shanmiteko/LotteryAutoScript#4]
## 想在  [otketo](https://cloud.okteto.com/) 上部署，但是compose不会写[苦笑]
![image](https://user-images.githubusercontent.com/76923303/126487902-c47adc94-fc61-4d3d-8193-5db574e49b0b.png)

**Comment by shanmiteko** [comment]
参考我这个一键脚本操作[docker init](https://github.com/shanmiteko/LotteryAutoScript/blob/main/script/docker/init.sh)

难点在于如何进行数据卷挂载

**Comment by shanmiteko** [comment]
可以试一下from git

**Comment by 888haobing** [comment]
git试过了，失败了

**Comment by 888haobing** [comment]
volumeMounts:
         - name: nobb-mount
           mountPath: /nobb
      volumes:
       - name: nobb-mount
         persistentVolumeClaim:
            claimName: sys-pvclaim

**Comment by 888haobing** [comment]
貌似可以这样

**Comment by shanmiteko** [comment]
有错误截图吗，我帮你看看

**Comment by 888haobing** [comment]
volumes: 
            - /data/

这样挂载数据不会丢失

**Comment by shanmiteko** [comment]
这个otketo能跑shell命令吗

**Comment by 888haobing** [comment]
有cl工具

**Comment by 888haobing** [comment]
大佬可以上他们网站试试

**Comment by shanmiteko** [comment]
什么个意思，那不直接输入
```sh
curl -fsSL https://cdn.staticaly.com/gh/shanmiteko/LotteryAutoScript/main/script/docker/init.sh | sh
```
就完事了

**Comment by 888haobing** [comment]
https://okteto.com/docs/getting-started/installation/

**Comment by 888haobing** [comment]
这个是他们的doc

**Comment by 888haobing** [comment]
![image](https://user-images.githubusercontent.com/76923303/126609351-2f973843-4a04-4327-8a78-5d0567358276.png)
错误日记

**Comment by shanmiteko** [comment]
![image](https://user-images.githubusercontent.com/87006121/126886376-c65194b3-b9a7-4c9f-afaf-c07f7023230a.png)
![image](https://user-images.githubusercontent.com/87006121/126886391-94211517-39ef-41bf-890d-859e5972cfe8.png)
okteto不适合跑这个任务，网络请求可能有限制，而且需要定时触发
