### ISSUE TITLE
希望可以实现转发视频以防被抽奖机器过滤的时候，抄写一下转发视频下面的热评。

### ISSUE THREAD

**Issue by xdchm0719** [shanmiteko/LotteryAutoScript#406]
### 描述

希望可以实现转发视频以防被抽奖机器过滤的时候，抄写一下转发视频下面的热评。

**Comment by ypw96** [comment]
感觉没啥必要。转发视频主要是为了防止被开奖脚本过滤掉。如果真要去主页查成分，基本上你转发视频带热评也会被鉴定为机器人

**Comment by shanmiteko** [comment]
> 感觉没啥必要。转发视频主要是为了防止被开奖脚本过滤掉。如果真要去主页查成分，基本上你转发视频带热评也会被鉴定为机器人

赞同
