### ISSUE TITLE
大家会掉关注吗，我也不懂为什么总是掉关注

### ISSUE THREAD

**Issue by xiaoyiying** [shanmiteko/LotteryAutoScript#408]
### 描述Bug

大家会掉关注吗，我也不懂为什么总是掉关注，
就是已经关注了的，过段时间或者过几天一看又没关注了，同一个up私信关注自动回复一大堆
找不到原因，大家有没有遇到过这问题

### 重现Bug

1

### 预期行为

1

### 运行日志

1

### 操作系统

1

### 脚本版本

1

**Comment by xiaoyiying** [comment]
从未打开过清理关注和动态的功能

**Comment by shanmiteko** [comment]
有的up会手动移除关注
