### ISSUE TITLE
验证码识别，一直显示尝试重新连接

### ISSUE THREAD

**Issue by xdchm0719** [shanmiteko/LotteryAutoScript#410]
### 描述Bug

[请求失败]原因:connect ECONNREFUSED 127.0.0.1:9898 尝试重新连接中...
[请求失败]原因:connect ECONNREFUSED 127.0.0.1:9898 尝试重新连接中...

docker也重新拉了。

### 重现Bug

验证码识别，一直显示尝试重新连接

### 预期行为

[请求失败]原因:connect ECONNREFUSED 127.0.0.1:9898 尝试重新连接中...
[请求失败]原因:connect ECONNREFUSED 127.0.0.1:9898 尝试重新连接中...

### 截图

青龙面板日志
![image](https://github.com/user-attachments/assets/30174b2b-913c-4e94-9d36-6bc6854cae47)

docker验证码识别日志
![image](https://github.com/user-attachments/assets/5af92df0-6527-48f8-bae1-cf023241fb00)

### 运行日志

[请求失败]原因:connect ECONNREFUSED 127.0.0.1:9898 尝试重新连接中...
[请求失败]原因:connect ECONNREFUSED 127.0.0.1:9898 尝试重新连接中...

### 操作系统

CentOS

### NodeJs版本

v22.2.0

### 脚本版本

v2.9.1

**Comment by shanmiteko** [comment]
验证码服务不对

**Comment by xdchm0719** [comment]
> 验证码服务不对

请问哪里不对啊。

**Comment by shanmiteko** [comment]
> > 验证码服务不对
> 
> 请问哪里不对啊。

是我那个OCR服务吗
