### ISSUE TITLE
评论失效，无法评论

### ISSUE THREAD

**Issue by wj988** [shanmiteko/LotteryAutoScript#411]
### 描述Bug

代码正常运行，显示已评论成功，但从已转发的动态中无该已评论文字

### 重现Bug

原先正常使用，未进行变更

### 预期行为

无

### 运行日志

    "uid": [
        324430888
    ],
    "dyid": "968362224417505296",
    "relay_chat": "转发动态",
    "ctrl": "[]",
    "chat_type": 11,
    "rid": "326314007",
    "chat": "好运~"
}
]]
[2024-08-25T07:03:57.751+08] [Info] [帐号1 自动评论] [评论成功: 好运~]

### 操作系统

win10

### 脚本版本

最新

**Comment by shanmiteko** [comment]
可能被系统吞了

**Comment by wj988** [comment]
都正常，昨天21点后，不知道改了什么，就不行了，不排除是吞了，但有其他未知原因

**Comment by wj988** [comment]
多位群友，都是这种情况
