### ISSUE TITLE
每次打开软件都提示暂无抽奖信息怎么办

### ISSUE THREAD

**Issue by xiaobu159** [shanmiteko/LotteryAutoScript#412]
### 描述Bug

每次打开软件都提示暂无抽奖信息怎么办
![1724587472122](https://github.com/user-attachments/assets/8883e2b3-76d1-45cc-ae46-d693bd214420)

### 重现Bug

每次打开软件都提示暂无抽奖信息怎么办

### 预期行为

每次打开软件都提示暂无抽奖信息怎么办

### 截图

![01881e1a5ce421fe26f36ccffe5359b5](https://github.com/user-attachments/assets/5e0e8329-1925-4edd-847f-8e4a4062c512)

### 运行日志

每次打开软件都提示暂无抽奖信息怎么办

### 操作系统

Win11

### 脚本版本

2.9.1

**Comment by lll666666** [comment]
不清楚，我手动的有

**Comment by xiaobu159** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by xiaobu159** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
