### ISSUE TITLE
有些抽奖动态有点赞或三连需求

### ISSUE THREAD

**Issue by xiaobuboy** [shanmiteko/LotteryAutoScript#415]
### 描述

有些抽奖动态有点赞或三连需求，能不能识别这些关键字，有“赞”或者“三连”就给这条动态自动点赞或自动三连，并且这功能可以按需求选择开启或关闭

**Comment by shanmiteko** [comment]
动态怎么三连，他能知道你三连了吗

**Comment by xiaobuboy** [comment]
查了一下，作者只能看到点赞，三连确实不需要
