### ISSUE TITLE
ocr启动不运行，救救孩子吧

### ISSUE THREAD

**Issue by wufashiyong11** [shanmiteko/LotteryAutoScript#417]
### 描述Bug

运行抽奖脚本后，ocr没有运行，没有显示[账号1 验证码识别]

### 重现Bug

1,启动ddddocr-fastapi-main\app\main.py
2,启动抽奖脚本
![0d82756b49abab1debf699eca0d316d](https://github.com/user-attachments/assets/c070e1b6-3918-4b58-b27d-64d20cc15279)

### 预期行为

没有显示[账号1 验证码识别]

### 截图

![5c0e5f7c1e1d24438a60fc44e1e4e18](https://github.com/user-attachments/assets/e35e005d-8400-4cc0-a6e3-d31bfee0dc62)

### 运行日志

![940674c064636af234bf59596579ce3](https://github.com/user-attachments/assets/f52bbdbb-8c61-4691-bc21-331561118e5a)
![0d82756b49abab1debf699eca0d316d](https://github.com/user-attachments/assets/2fcb8038-7b96-4c04-95f9-b65714f3e6b0)

### 操作系统

win10

### NodeJs版本

Nodejs: v18.5.0

### 脚本版本

v2.9.1

**Comment by wufashiyong11** [comment]
是不是因为没有成功运行ocr的原因所以评论没有成功发出？
虽然显示自动评论，但是我用小号看，看不到自己的评论，试过2-3个号用脚本跑，都不显示评论

**Comment by wufashiyong11** [comment]
我纯小白o(╥﹏╥)o

**Comment by wufashiyong11** [comment]
![3b990a37a0f9ab3d256bb38ad5e32ef](https://github.com/user-attachments/assets/ce84dbbb-33f8-45f7-bc71-d0b7b6829ff1)

**Comment by wufashiyong11** [comment]
还需要提供啥，不太懂o(╥﹏╥)o...ddddor是跟着教程下的，不过就是下了之后不太一样，显示的8000端口，防火墙也开放了8000的端口，脚本我用的是lottery-auto-script-node18-win-x64 .zip
![0ca745b093e80e6f077ae0b05bfd44f](https://github.com/user-attachments/assets/703eaa1a-1a9e-4a75-af41-36c17a1cee1f)
![6c49d085ed3a563a6b3ff58e0ff2212](https://github.com/user-attachments/assets/0c4cc430-c104-45c9-b728-aca049d83e0d)
![6ca9a5a0fe5b2e702fd890a50422f7b](https://github.com/user-attachments/assets/6af206bd-1bdf-4934-a75d-bb30333cb7d6)
![28dc02c881665d5cd52ec198880bb4f](https://github.com/user-attachments/assets/68d2d25f-a0c9-479f-8bae-8d19db1a78eb)

**Comment by wufashiyong11** [comment]
还跟着教程弄了docker，但是我只会安装不会用😭😭😭，我是跟着教程直接启动的没有设置图3的内容，用docker设置的这个http://172.17.0.2:9898，也没啥反应😭😭😭
![9b1d9d30b6caa64547768de050f1c4c](https://github.com/user-attachments/assets/550189f2-24f4-4906-aa06-2e5cac991517)
![c1f9ad79c43c03b00a9d6a6d39e46f3](https://github.com/user-attachments/assets/a6ec5396-ca93-47b1-8606-d8c44baa56b1)
![808190db21418cac521dfab4c659050](https://github.com/user-attachments/assets/f6189393-7abf-44d4-abc1-f894356048ed)
![4ec64387700a4eca09013052c5d713b](https://github.com/user-attachments/assets/2d2db105-d183-4bdc-bae8-ef3c192ecb76)

**Comment by wufashiyong11** [comment]
也是不运行
![38be35dc06e4311e3226b287f210dc7](https://github.com/user-attachments/assets/7eaca7e3-4b2a-4ab6-9412-6264a0b6ec09)
![fdbd153b98341af6ce119d4935e88ce](https://github.com/user-attachments/assets/3441b4af-22a8-4730-9912-52fa8ac299d5)

**Comment by shanmiteko** [comment]
评论要验证码才会运行

**Comment by wufashiyong11** [comment]
大概懂了，但是为啥评论不显示，就算不报错也不显示，是不是转发频率太快了😭😭😭而且会被制裁1天都发不出评论，就算过1天用插件检查评论也无法通过无账号找到是通过什么链接找到的
