### ISSUE TITLE
第二个号不会转发第一个号转发过的

### ISSUE THREAD

**Issue by 2083779614** [shanmiteko/LotteryAutoScript#421]
### 描述Bug

第二个号不会转发第一个号转发过的，导致第二个号什么都没有转发

### 重现Bug

![Quicker_20241017_172656](https://github.com/user-attachments/assets/03e52da6-5e2b-49ab-b534-f5c63f43c6a7)
![Quicker_20241017_172719](https://github.com/user-attachments/assets/13f9bf92-f892-4059-bab7-f982bbcdd4e8)

### 预期行为

![Quicker_20241017_172656](https://github.com/user-attachments/assets/7f741d4b-8b9d-49bb-b32d-df6090bf2d2e)

### 截图

![Quicker_20241017_172719](https://github.com/user-attachments/assets/ea9a1e33-c521-48f0-976a-6335a3e77afe)
![Quicker_20241017_172656](https://github.com/user-attachments/assets/d9512b16-60b9-4ce3-aa86-ae55218a353a)

### 运行日志

![Quicker_20241017_172719](https://github.com/user-attachments/assets/0ec132e0-4504-43a9-a7dc-a6613b64c9a1)

### 操作系统

青龙面板

### 脚本版本

2.9.1

**Comment by shanmiteko** [comment]
设置是否正确

**Comment by 6587556** [comment]
我也是，第二个就转发了一条结束了！三一样。四又可以了。以前不会啊
