### ISSUE TITLE
分区移动失败

### ISSUE THREAD

**Issue by lll666666** [shanmiteko/LotteryAutoScript#423]
### 描述

![image](https://github.com/user-attachments/assets/5e121bb2-1e86-4af9-951a-94a6c18c9d6a)
![image](https://github.com/user-attachments/assets/71d513d3-aa1e-40cf-bcfd-2b7d003c223d)
出现22105为未关注，能否添加一个出现这个报错再次尝试关注

**Comment by lll666666** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/e5fbfed42807605115c6a9b96447f6328ca263c5/docs/user/relation.md

**Comment by xzlosats111** [comment]
好久没检查，今天去检查一下，才发现这大半个月每天都只转发非常少的动态，发现是有相同报错后就停止运行不再转发了了
感觉也不是一个很致命的错误，但是导致停止运行，话说这是策略作者手动设计的还是本身就会无法继续运行，所以有一个比较狠的想法，考虑到经常会报各种各样的错误，能不能设计一个策略就是遇到所有无法处理的错误，只要程序还能运行就不处理，直接强行运行下去，以防出现类似的情况
