### ISSUE TITLE
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...

### ISSUE THREAD

**Issue by karhow** [shanmiteko/LotteryAutoScript#424]
### 描述Bug

<img width="488" alt="image" src="https://github.com/user-attachments/assets/bc16d838-30cd-4873-9341-546a1913c3e4">

这是什么原因？IP黑了吗？山特米

### 重现Bug

如图

### 预期行为

正常搜索动态

### 运行日志

[2024-11-06T14:58:28.470+08] [Info] [帐号1 获取关注列表] [成功]
[2024-11-06T14:58:28.472+08] [Info] [帐号1 获取动态] [开始获取含关键词抽奖合集的专栏信息]
[2024-11-06T14:58:28.728+08] [Info] [帐号1 搜索专栏] [成功 关键词: 抽奖合集]
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[2024-11-06T14:59:29.912+08] [Info] [帐号1 获取动态] [提取专栏(39706360)中提及的dyid(0)]
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[2024-11-06T15:00:31.186+08] [Info] [帐号1 获取动态] [提取专栏(39706010)中提及的dyid(0)]
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[2024-11-06T15:01:32.349+08] [Info] [帐号1 获取动态] [提取专栏(39705778)中提及的dyid(0)]
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...
[不期待响应]原因:HTTP状态码: 412 尝试重新请求中...

### 操作系统

linux 青龙容器

### NodeJs版本

v17.5.0 

### 脚本版本

最新版 v2.9.1

**Comment by shanmiteko** [comment]
触发风控了
