### ISSUE TITLE
转发如果有多个关键词，如何设置脚本对每个关键词都检索一篇专栏

### ISSUE THREAD

**Issue by jkluio78** [shanmiteko/LotteryAutoScript#43]
### 描述

假设监控专栏的关键词有3个，现在想每个关键词的专栏都只检索一篇，即搜索含A、B、C的关键词的专栏各一篇，现版本是否支持？如果支持，如何设置参数？下面的设置只检索了一篇含A的专栏就不再继续检索了

        /**
         * 监视的专栏关键词
         */
        Articles: [
            'A',
            'B',
            'C'
        ],
        /**
         * - 获取专栏数量
         */
        article_scan_page: 1,

**Comment by shanmiteko** [comment]
支持的，可能哪里出错了

如果可以请附上脱敏后的日志信息

**Comment by jkluio78** [comment]
我手动运行了一下，这个功能没问题，之前运行应该是风控了。生成随机动态我选择的是转发视频，我发现转发视频的时延（2000ms）有点短，可能是运行时被风控了，这个时延可以设置吗？
还有my_config里面的检索动态间隔修改了好像没起作用？
![image](https://user-images.githubusercontent.com/74967641/136671573-99df6224-7100-4044-be35-3c0a1e3b3396.png)
