### ISSUE TITLE
希望有LOG日志提供随机动态发的什么

### ISSUE THREAD

**Issue by davidelectricfree** [shanmiteko/LotteryAutoScript#47]
### 描述

  我在my_config中设置了大概几十张图片，非常单纯的风景图，但是有一个问题，总会一段时间，会随机到某张图片，被B站自动删除，说这张图片违反了社区规则（我也不知道风景画怎么被判定违规的，全都是爬的bing每日壁纸的图片，单纯的风景画不能再单纯了），因为B站会删除这个图片，而且只告诉我删除动态的ID，我不知道究竟是哪张图片有问题，我想找出这张图片，但是因为没有LOG日志，找不出来，看能不能让程序输出那种能够提供随机动态发的哪张图片的LOG日志，避免账号多次出现社区违规的行为。（听说多次出现社区违规会被封号，也不知道是不是真的，希望能够提供这种功能，让我能通过LOG日志，可以找出具体是哪张图片违规，把他从config文件中删除）

**Comment by davidelectricfree** [comment]
> 
> 
> 图片的源必须是这种格式`https://i0.hdslb.com/bfs/album/*.*`

是的，现在发图片没有任何问题，就是某一张会出现违规信息

**Comment by shanmiteko** [comment]
用`>>`输出日志

**Comment by shanmiteko** [comment]
应该是图片消息，忘记序列化了
