### ISSUE TITLE
请求优化逻辑

### ISSUE THREAD

**Issue by wulifuji** [shanmiteko/LotteryAutoScript#49]
### 描述

![image](https://user-images.githubusercontent.com/61496038/137159856-8794d3ad-b696-47b0-a646-cfaa6ccc00d6.png)
如图，在start运行检查专栏时，会先检查动态细节，再判断是否转发过；是否可优化为获取专栏提及动态后，与已转发动态求交集，判断是否达到跳过阈值，再逐个检查未转发动态

**Comment by shanmiteko** [comment]
那么怎么快速获取已转发动态
