### ISSUE TITLE
DOCKER部署

### ISSUE THREAD

**Issue by Mortal520** [shanmiteko/LotteryAutoScript#5]
docker部署命令挂了

[root@onRdWlIRgb home]# curl -fsSL https://cdn.staticaly.com/gh/shanmiteko/LotteryAutoScript/main/script/docker/init.sh | sh
curl: (6) Could not resolve host: cdn.staticaly.com; 未知的错误

**Comment by shanmiteko** [comment]
多试几次
或者
https://github.com/shanmiteko/LotteryAutoScript/raw/main/script/docker/init.sh
https://raw.fastgit.org/shanmiteko/LotteryAutoScript/main/script/docker/init.sh
https://cdn.jsdelivr.net/gh/shanmiteko/LotteryAutoScript@main/script/docker/init.sh
