### ISSUE TITLE
up关闭评论区的能跳过评论

### ISSUE THREAD

**Issue by glowingtorch** [shanmiteko/LotteryAutoScript#52]
### 描述

遇到关闭评论区的动态会报错然后尝试评论，间隔还会逐渐加长
未知错误
["code":12061,"message" :"UP主已关闭评论区" 
这种已知是关评论的不应该再尝试评论

**Comment by shanmiteko** [comment]
是哪条动态

完整日志

**Comment by glowingtorch** [comment]
![QQ图片20211015123552](https://user-images.githubusercontent.com/74662271/137432856-471aa2bf-6863-405a-ae5b-ffc6b79fe178.png)

**Comment by glowingtorch** [comment]
581328406250695669
