### ISSUE TITLE
关于取关功能的一些建议

### ISSUE THREAD

**Issue by glowingtorch** [shanmiteko/LotteryAutoScript#6]
### 清晰而简明地描述
在此写下你的描述
清理关注功能，按关注时间从前往后，检测一页动态看有没有关键字‘抽’或者‘送’，再取关，漏的少量可以手动清理
不用跟清理动态绑在一起，动态其实清不清无所谓，只按天数来会取关大量还有未开奖的up。

**Comment by shanmiteko** [comment]
了解现在的清理机制吗，请先查看`my_config.example.js`文件关于清理的设置

不会取关到未开奖的up具体请查看`lib/clear.js`文件
