### ISSUE TITLE
转发时报错：“该动态不能转发分享”

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#60]
### 描述Bug

转发时报错：“该动态不能转发分享”
并且“停止抽奖，原因：转发失败”

### 重现Bug

转发抽奖过程中

### 预期行为

不知道

### 截图

![6C5FD68E-3C20-458B-BE3F-DF2A247BEE5B](https://user-images.githubusercontent.com/49329079/139539615-9b6605fe-05f8-4e15-8060-9890ed96f262.jpeg)

### 运行日志

如图

### 操作系统

win10

### 脚本版本

2.2.9

**Comment by SleepCC** [comment]
补充一下，应该是这三个动态导致的
https://t.bilibili.com/587273285229217499?tab=2
https://t.bilibili.com/586902462046170689?tab=2
https://t.bilibili.com/586531071931278983?tab=2
