### ISSUE TITLE
检查是否中奖会推送含有过滤词的私信

### ISSUE THREAD

**Issue by jkluio78** [shanmiteko/LotteryAutoScript#62]
### 描述Bug

有些预约抽奖中奖后UP不会私信，故而想添加关键词，让脚本连带一起检查有没有预约抽奖中奖。但是添加后却推送了预约抽奖和直播开始的非中奖消息，而这些信息含有`预约成功`的屏蔽字却没有被脚本过滤掉。

### 重现Bug

**1.检查中添加了关键词`有奖预约开奖通知`**
![image](https://user-images.githubusercontent.com/74967641/139628632-41fb9dee-3d61-4a03-ac16-ade626ac79fd.png)

**2.脚本检查推送消息，推送了预约抽奖和直播开始的非中奖消息，这些信息含有`预约成功`的屏蔽字却没有被脚本过滤掉。
同时中奖消息中共同含有的字词是`开奖`，和脚本中相关联的关键字只有我添加的`有奖预约开奖通知`中的`开奖`。是否是因为我添加了这个新关键词导致没有过滤掉呢？**
![image](https://user-images.githubusercontent.com/74967641/139629588-cc33284c-99b9-4fb0-a017-0948523dbefd.png)

### 预期行为

不推送含有过滤词的中奖信息，过滤机制不受后面的关键词影响

### 运行日志

无

### 操作系统

win10

### 脚本版本

v2.3.1

**Comment by shanmiteko** [comment]
请提供一下你的相关设置

**Comment by shanmiteko** [comment]
这个关键字的权重是逐级升高的，所以后面的规则会覆盖之前的

判断的是`|`分割的整个词语

可能是其他关键词触发的？

**Comment by jkluio78** [comment]
我重新检查了一下，有两个消息存在`大会员`所以被推送了，不是脚本的问题
为了不推送类似消息，过滤词我放到最后好了
