### ISSUE TITLE
过滤专栏存在bug

### ISSUE THREAD

**Issue by jkluio78** [shanmiteko/LotteryAutoScript#67]
### 描述Bug

![image](https://user-images.githubusercontent.com/74967641/140902885-2732d7cc-8d05-45cd-803b-50e466120c67.png)

**今天发布的专栏也被过滤**

**看了下代码，我觉得解决办法是先获取当前时间戳`now_time`
`now_time = Math.floor(Date.now() / 1000)`
然后部分代码的修改如下
`if (now_time - pub_time / 86400 > article_create_time) {`**
![image](https://user-images.githubusercontent.com/74967641/140903558-418fc8b4-ed75-45a3-a536-d16615576a12.png)

**需要注意 抓包获取的时间戳位数是10位，因此代码获取的当前时间戳也应该是10位，不然相减会出错**
![image](https://user-images.githubusercontent.com/74967641/140904432-cd5f667d-9d62-4ea5-ade0-e483f2b379a9.png)

### 重现Bug

无

### 预期行为

无

### 运行日志

无

### 操作系统

win10

### 脚本版本

v2.3.3

**Comment by shanmiteko** [comment]
大意了，你能提交pr帮改一下吗

**Comment by jkluio78** [comment]
> 大意了，你能提交pr帮改一下吗

好的，等等我改好就PR
