### ISSUE TITLE
优化API获得的动态转发

### ISSUE THREAD

**Issue by spiritLHL** [shanmiteko/LotteryAutoScript#69]
### 描述

注意到从API获得的动态还需要检索一次内容再转发，请问能否加个配置无需检索内容无脑转发获得的动态

**Comment by spiritLHL** [comment]
转发不成功自动跳到下一动态转，没有间隔，这样能缩短转发时间，不知道会不会频繁

**Comment by shanmiteko** [comment]
判断动态是否转发，要获取一次动态细节

**Comment by shanmiteko** [comment]
> 转发不成功自动跳到下一动态转，没有间隔，这样能缩短转发时间，不知道会不会频繁

把所有的等待时间都调为0

**Comment by spiritLHL** [comment]
好的，我试试，如果获取动态细节也保存云端就好了，不用再次获取了

**Comment by shanmiteko** [comment]
> 好的，我试试，如果获取动态细节也保存云端就好了，不用再次获取了

要判断是否点赞，存不了
