### ISSUE TITLE
显示账号异常，点赞失败，且参与抽奖较少

### ISSUE THREAD

**Issue by sjfhsjs** [shanmiteko/LotteryAutoScript#7]
### 在反馈bug之前，请确保你已经认真阅读了本项目的README和脚本的内置说明
**描述bug**  
bug1:个别动态出现“点赞失败，账号异常”字样。
bug2:每天只能收集到个位数的动态进行转发。

**重现bug**  
说明您在进行了怎样的操作后出现了bug
bug1： 正常启动后，会随机出现，具有偶然性。
bug2：正常启动后，只转发2-3条动态就显示无抽奖，为控制变量，做了无设置的config对比，仍然只转发两条。

**预期行为**  
简要描述进行以上操作后预期的脚本行为
无

**截图**  
下图为bug1
![QQ图片20210730004044](https://user-images.githubusercontent.com/51836481/127531915-7427eab5-8078-4650-8bf8-f37332870a93.png)

下图为bug2，这是第三次打开脚本只转发了1条动态，且与上一次重复，怀疑bug与此有关。
![QQ图片20210730004029](https://user-images.githubusercontent.com/51836481/127531702-1202fa3c-a2c4-4993-bede-43ddcde4dd92.png)

**运行日志**  
控制台日志。  
没找到。

**使用环境:**  
 本地运行

**其他**  
若您有其他想要补充的内容，请在此说明

**Comment by shanmiteko** [comment]
这个截图就是控制台日志

使用环境应包括，操作系统，脚本版本，网络情况

你这个可能是账号异常了，是否能手动执行抽奖任务

**Comment by sjfhsjs** [comment]
脚本版本最近几个版本全试了，都是一样的情况，
操作系统就是windowx64
可以手动抽奖，网页脚本也可以正常转发，比本地多很多




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shanmiteko/LotteryAutoScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月30日(星期五) 上午8:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shanmiteko/LotteryAutoScript] bug反馈 (#7)





 
这个截图就是控制台日志
 
使用环境应包括，操作系统，脚本版本，网络情况
 
你这个可能是账号异常了，是否能手动执行抽奖任务
