### ISSUE TITLE
对接的后端系统有设置接口2秒内访问的数量限制，这边可能需要一个2~3秒请求失败的再次请求的功能

### ISSUE THREAD

**Issue by spiritLHL** [shanmiteko/LotteryAutoScript#73]
### 描述

后端系统为防止恶意攻击，限制了每2秒150000次请求限制，请问这边有API请求失败得到空数据隔几秒再请求多次的功能吗？

**Comment by spiritLHL** [comment]
![](https://i.loli.net/2021/11/27/p4kSrE9NVIDq2cO.png)
类似的，我写了
![](https://i.loli.net/2021/11/27/bTAa7ZPrCfJ2jXc.png)
![](https://i.loli.net/2021/11/27/N7sZlLentqJGUk5.png)
效果就是达到短时间内访问次数一定限制后续不会返回东西只会在我这打印日志，客户端收不到任何数据。

**Comment by shanmiteko** [comment]
这个`RateLimiter`的生成位置？

**Comment by spiritLHL** [comment]
所有端口

**Comment by spiritLHL** [comment]
我打包一份发你吧，也许你看的更明白点

**Comment by shanmiteko** [comment]
普通使用一般不会频繁吧，你这个只是针对某个IP限制

**Comment by spiritLHL** [comment]
针对访问我IP接口的次数限制，不同IP访问我IP是累计在一起的

**Comment by shanmiteko** [comment]
> 这个`RateLimiter`的生成位置？

图上的`RateLimiter`位置不太对，每次请求都重新生成一个？

**Comment by spiritLHL** [comment]
好像是我的锅，该在外面单独写的。。。

**Comment by spiritLHL** [comment]
异步在里头不是异步在外面

**Comment by spiritLHL** [comment]
改好了，实际是需要一个访问超时判断，超时没东西返回暂停访问一会再访问的功能

**Comment by shanmiteko** [comment]
被限制的情况多吗，不多就不用加了><

**Comment by spiritLHL** [comment]
暂时没出现，主要是有时候我这边后端可能不稳定崩了，没数据回传，写个超时尝试或者跳过好点

**Comment by shanmiteko** [comment]
超时？那好办

**Comment by shanmiteko** [comment]
有默认超时重传

**Comment by spiritLHL** [comment]
私发你具体中转的后端源码和后端接口文档地址了，应该没啥问题了
