### ISSUE TITLE
爬取到的加码动态没有上传存储到云端API里，导致爬取转发比API转发多

### ISSUE THREAD

**Issue by spiritLHL** [shanmiteko/LotteryAutoScript#74]
### 描述Bug

设置监控爬取到的加码动态没有上传存储到云端API里，导致爬取转发动态量比API转发多，请求修复上传加码动态

### 重现Bug

设置了监控，转了加码动态
没设置监控，设置了API，没转加码动态

### 预期行为

一样的筛选条件
一个设置了监控，没设置了API，转了加码动态
一个没设置监控，设置了API，没转加码动态

### 截图

![](https://s3.bmp.ovh/imgs/2021/11/8fdf5d9de678ed53.jpg)

![](https://s3.bmp.ovh/imgs/2021/11/a42ad45b42a49317.jpg)

### 运行日志

无法在日志中看到，但从转发量可以看出来

### 操作系统

win server2019

### 脚本版本

2.3.5

**Comment by shanmiteko** [comment]
提供一下获取动态的API的链接

**Comment by spiritLHL** [comment]
> 提供一下获取动态的API的链接

群公告。。。群公告的链接

**Comment by shanmiteko** [comment]
确定不是其他设置的问题？

![图片](https://user-images.githubusercontent.com/87006121/143672549-c6157da6-9ab4-42f3-a1ea-41dd3dabe1db.png)

**Comment by spiritLHL** [comment]
主要是有群友反馈，说是少了不少，我叫他联系你吧，晚上他和你聊吧
