### ISSUE TITLE
看见提到https://render.com/

### ISSUE THREAD

**Issue by qwnz** [shanmiteko/LotteryAutoScript#76]
### 描述

这个的时间限制好像是指web网站的，他还提供那个sevice好像是不限时间

**Comment by shanmiteko** [comment]
Duplicate of #75 
![图片](https://user-images.githubusercontent.com/87006121/143833926-2259c865-62e0-4fc3-929c-613ec4aa5a43.png)
https://render.com/pricing
> Web services on the free plan are automatically spun down after 15 minutes of inactivity. When a new request for a free service comes in, Render spins it up again so it can process the request.
免费计划中的网络服务在15分钟的非活动时间后会被自动关闭。当一个免费服务的新请求进来时，Render会再次启动它，以便它能处理该请求。

**Comment by shanmiteko** [comment]
这个用来放静态网站和搭网站后台可以，运行这个脚本不太行（免费部分）
