### ISSUE TITLE
未观看视频就直接进行点赞评论抽奖极易导致‘账号异常：点赞失败’，并且按照现有逻辑会重复尝试转发

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#82]
### 描述Bug

①在未观看视频的情况下，脚本进行视频抽奖，很容易触发 账号异常：点赞失败
②在已经账号一场的情况下，会有大量获取到但未转发的视频抽奖堆积，按照现在 用是否点赞判断转发的逻辑 会重复转发，越来越黑，效果如图

### 重现Bug

视频类型的抽奖

### 预期行为

在配置项中加入 屏蔽所有视频抽奖 的选项，并且此开关最好默认写为开启状态

### 截图

![image](https://pic2.58cdn.com.cn/nowater/webim/big/n_v24572bd0384394adf8d52fedcc72f881a.jpg)

### 运行日志

无

### 操作系统

win10

### 脚本版本

2.3.9

**Comment by shanmiteko** [comment]
> ①在未观看视频的情况下，脚本进行视频抽奖，很容易触发 账号异常：点赞失败

如果观看过就不会异常吗

**Comment by spiritLHL** [comment]
> > ①在未观看视频的情况下，脚本进行视频抽奖，很容易触发 账号异常：点赞失败
> 
> 如果观看过就不会异常吗

可以测试测试

**Comment by shanmiteko** [comment]
> > > ①在未观看视频的情况下，脚本进行视频抽奖，很容易触发 账号异常：点赞失败
> > 
> > 如果观看过就不会异常吗
> 
> 可以测试测试

观看成功历史记录里就会有显示

**Comment by jzcangshu** [comment]
> > > > ①在未观看视频的情况下，脚本进行视频抽奖，很容易触发 账号异常：点赞失败
> > > 
> > > 
> > > 如果观看过就不会异常吗
> > 
> > 
> > 可以测试测试
> 
> 观看成功历史记录里就会有显示

网页版有暂停历史纪录的功能，或许可以在抽奖时自动临时打开，结束后关闭？
或者干脆加入配置项，让不在意的用户自己选择开启

因为我自己在手机上用同一个账号去点赞这些视频是没问题的，因为一点进去就会自动播放，然后再点赞，目前相同的视频点赞时都没有再出现异常
