### ISSUE TITLE
请求动态接口错误后直接结束当前账号

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#85]
### 描述Bug

请求获取动态数据的后端接口遇到网路错误，就直接跳过账号了

### 重现Bug

使用服务器动态数据抽奖

### 预期行为

在当前账号继续重试请求直至正常（反正后端网络错误换号也不可能解决，还会导致账号短时间内重复切换）

### 截图

![](https://s3.bmp.ovh/imgs/2021/12/4f4622bbdf8470ea.jpeg)

### 运行日志

如图

### 操作系统

win10

### 脚本版本

2.4.0

**Comment by shanmiteko** [comment]
@spiritLHL this way

**Comment by spiritLHL** [comment]
无解，后端频繁炸裂的原因我至今没搞明白，如果有时间我会再次检查到底哪里出了问题
