### ISSUE TITLE
如果对效率影响不大，希望能增加 用点赞和dyids混合判断转发状态的方式

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#86]
### 描述

当前只能选择一个模式，一旦切换模式就会导致之前判断的全部失效，希望能加入混合判断模式：即依旧点赞所有已转发动态，在判断时也使用本地存储dyids和点赞混合判断（满足一者即可）作备份和防止点赞失败导致重复转发

谢谢大佬阿里嘎多:D

**Comment by shanmiteko** [comment]
点赞容易异常，本地使用就用模式1

**Comment by jzcangshu** [comment]
好滴
