### ISSUE TITLE
公共黑名单参数设置无效

### ISSUE THREAD

**Issue by SleepCC** [shanmiteko/LotteryAutoScript#87]
### 描述Bug

把公共黑名单参数设置成false后，仍然会使用公共黑名单

### 重现Bug

如描述

### 预期行为

设置正常起作用

### 截图

![image](https://user-images.githubusercontent.com/30489595/145663788-e6a50eea-870b-4eee-a358-6046c7cf94f8.png)
![image](https://user-images.githubusercontent.com/30489595/145663794-fee60c29-8d59-408c-98ad-d6c320ede839.png)

### 运行日志

如截图

### 操作系统

win10

### 脚本版本

2.4.0

**Comment by shanmiteko** [comment]
blacklist那栏是否为空

**Comment by SleepCC** [comment]
![image](https://user-images.githubusercontent.com/30489595/145664109-4a0f67f3-4202-4d03-a34c-f84c6c90edd4.png)
有黑名单

**Comment by shanmiteko** [comment]
功能没问题，日志里应该去掉“公共”两字

**Comment by SleepCC** [comment]
原来只是显示问题（
