### ISSUE TITLE
加码抽奖最后会出现undefined字符

### ISSUE THREAD

**Issue by SleepCC** [shanmiteko/LotteryAutoScript#88]
### 描述Bug

如标题

### 重现Bug

转发加码抽奖必定出现

### 预期行为

不出现undefined

### 截图

![image](https://user-images.githubusercontent.com/30489595/145666987-d1d64279-7818-4c61-a7d5-ac495392f999.png)

### 运行日志

无

### 操作系统

win10

### 脚本版本

2.4.0

**Comment by shanmiteko** [comment]
看看加码原动态内容
