### ISSUE TITLE
config与实际执行不符

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#89]
### 描述Bug

①本次的完整config设置为：[完整config（1）](https://hk.91io.cn/s/LyolESK) 
![76C6694F-62F1-4211-94B3-5375ABD8638D](https://user-images.githubusercontent.com/49329079/145682801-6c2271c3-31c6-4a8d-b5b7-cbd807d17ff3.jpeg)
设置了通过dyids判断是否转发，但是程序依旧在判断是否点赞

②本次的完整config设置为：[完整config（2）](https://hk.91io.cn/s/Y1KVahP) 
![79A1AD21-DC31-40B3-990B-02444CCC8F4D](https://user-images.githubusercontent.com/49329079/145682881-572d41b8-68b8-477b-a4f1-1e65496b57b4.jpeg)
设置了除账号1外所有账号使用接口获取数据，对账号单独进行B站爬取设置，但是程序启动后依旧获取了接口数据而不执行爬取

怀疑是不是还是之前的confug初始化问题？

### 重现Bug

start.bat

### 预期行为

不知道

### 运行日志

见上图

### 操作系统

win10

### 脚本版本

2.4.0

**Comment by jzcangshu** [comment]
2.4.2版本测试结果，依旧没有按照配置进行爬取：
![61A0AC91-E2E0-47D6-BD33-7CCBCC99CDDD](https://user-images.githubusercontent.com/49329079/145684359-7ee2d9aa-03e7-4304-a4da-5ef5a2d4cbeb.jpeg)

完整config（相对于②中配置只修改了is duplicated的判断方式为2）：https://hk.91io.cn/s/lyVWBhd

**Comment by shanmiteko** [comment]
> 设置了通过dyids判断是否转发，但是程序依旧在判断是否点赞

功能没问题，一些老代码未移除，只会在监视uid转发模式下触发

> 设置了除账号1外所有账号使用接口获取数据，对账号单独进行B站爬取设置，但是程序启动后依旧获取了接口数据而不执行爬取

设置里有两个config_1，后一个覆盖了前一个

**Comment by jzcangshu** [comment]
> 设置里有两个config_1，后一个覆盖了前一个

感谢，修改后的确正常了
