### ISSUE TITLE
希望可以修改现有爬取和转发穿插进行的运行顺序

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#91]
### 描述

```
也不知道为啥最近靠B站爬取获得数据的账号每次跑都会出现验证码（换了多次账号都出现，或许是B站更新了风控机制？）
感觉是由于快速调用多个不同API导致的，因为之前只用接口数据的账号连续转发大量动态也没有出现这个问题
或许可以通过改为纯爬取+纯转发的顺序运行，避免一个号连续长时间调用多API导致风控

我自己想了一个比较方便的解决方案，麻烦大佬看看是否可行👇
 ```

1. 允许env.js中填写的账号重复（比如说编号为“账号1”和”账号2“的，其实是填的同一个”账号A“）
2. 用config.js中的单独账号特殊设置功能，对”账号1“设置关闭转发只爬取，对”账号2“设置只转发。这样组合起来就可以实现对”账号A“先爬取再统一转发功能
3. 实现步骤②可能需要一项新功能：本地存储获取到的动态数据，或许就相当于把目前上传到后端的数据保存到本地，供自己多账号使用。然后再config.js里再加入一项配置项，填入存储已获取动态数据的文件位置。剩下的逻辑基本都不需要改动，也不需要大幅度更改已有代码逻辑。

**Comment by shanmiteko** [comment]
用一个号只上传数据，env里把抽奖功能关闭，其他号之后就可以直接从那个接口获取

**Comment by jzcangshu** [comment]
那这样干是不是就必须空挂一个账号 无法转发了---- 回复的原邮件 ***@***.***>发送日期2021年12月12日 19:37 ***@***.***> ***@***.******@***.***>主题Re: [shanmiteko/LotteryAutoScript] 希望可以修改现有爬取和转发穿插进行的运行顺序 (Issue #91)

用一个号只上传数据，env里把抽奖功能关闭，其他号之后就可以直接从那个接口获取



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/shanmiteko/LotteryAutoScript/issues/91#issuecomment-991881589",

"url": "https://github.com/shanmiteko/LotteryAutoScript/issues/91#issuecomment-991881589",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by shanmiteko** [comment]
不登录也可以爬动态，所以频繁的时候换一下IP就可
