### ISSUE TITLE
转发的动态后出现undefined

### ISSUE THREAD

**Issue by jzcangshu** [shanmiteko/LotteryAutoScript#95]
### 描述Bug

之前就有过这个问题 changelog中写已修复 但更新后依旧存在此问题

### 重现Bug

转发加码动态

### 预期行为

无

### 截图

![8029DB91-5B87-4500-B9F1-E0926F5EB203.jpeg](https://s2.loli.net/2021/12/19/oTa7IUDyQfA5G3e.jpg)

### 运行日志

无

### 操作系统

win10

### 脚本版本

2.4.4

**Comment by shanmiteko** [comment]
是否使用从API接口中获取动态的功能？

有人用老版本上传动态数据

**Comment by spiritLHL** [comment]
建议转发前去除动态中的屏蔽词，上传前也这么筛一下去除
