### ISSUE TITLE
建议推送  加上是第几个cookie的推送，账号1,2,3    

### ISSUE THREAD

**Issue by Serroro4** [shanmiteko/LotteryAutoScript#98]
### 描述

建议推送  加上是第几个cookie的推送，账号1,2,3

**Comment by Serroro4** [comment]
在邮件推送的第一行加上是第几个账号，账号1（uid）名字

**Comment by Serroro4** [comment]
新功能（想法）：有些开奖的话他有可能不at，这样的话可以   将所有   b站账号的名字   输出成一个日志，这样开奖是就便于看看是不是中奖

**Comment by ypw96** [comment]
其实就是中奖推送消息，私信是只有UID吧，毕竟@你的信息都能看到@的字，其实就是麻烦点，UID搜索下就能知道是哪个小号

**Comment by Serroro4** [comment]
图片上开奖的不@  所以需要知道所有账号的昵称，才能对着图片看看中没中

**Comment by ypw96** [comment]
图片开奖只能靠自己看啊，自己本地存一份所有账号名字啊，推送消息是不会推送私信没有关键词和没有@信息的账号啊.另外比如说没人@你和私信你，图片开奖，你咋知道你中奖了，就别提怎么去拿名字对照图片了。不过要求推送的信息最前面拼接个账号昵称我觉还是很不错的，有时候开奖2个号中了同一个，虽然推送了2条，但是看UID会认为自己已经检查过了，结果漏了一个号去领虽然是自己的问题。哈哈哈
